src/graphics/mesh_tools.cpp, src/graphics/stkmeshscenenode.cpp, src/states_screens/race_gui.cpp
Fix some warning when building with gcc 4.9.2.
=> Fix some warnings.

data/achievements.xml, src/achievements/achievement_info.hpp, src/items/swatter.cpp
=> Add a new achievement : Mosquito Hunter

lib/glew/CMakeLists.txt, lib/irrlicht/CMakeLists.txt, lib/irrlicht/source/Irrlicht/CIrrDeviceLinux.cpp, src/network/protocols/get_public_address.cpp, src/network/stk_host.cpp
Irrlich change also submitted upstream https://sourceforge.net/p/irrlicht/patches/300/.
=> FreeBSD build fixes.

data/optimize_data.sh
Changes include:
- Make each type of data optimization optional
- Multithread all data optimization
- Add B3D to B3DZ compression (disabled by default)
- Optimize images in many more ways
- More comments describing each section and some explanations
- Ability to vastly increase runtime for a few more mb saved (enabled by default; depends on types of optimizations used)
- Change to using bash instead of sh
- Probably a few more minor changes
=> Vastly improve data optimization script

lib/irrlicht/source/Irrlicht/CIrrDeviceLinux.cpp
=> Include unistd.h for usleep()

src/guiengine/skin.cpp, src/guiengine/widgets/spinner_widget.cpp, src/guiengine/widgets/spinner_widget.hpp
You can change slider/spinner's value by mouse click.
It works only on gauge spinners.
=> Sliders react to mouse

src/guiengine/skin.cpp, src/states_screens/options_screen_ui.cpp
Nothing more than the title says. Feel free to change the text.
=> Add a tooltip to explain usage of per-player handicaps

src/utils/debug.cpp
=> set "Adjust Lights" base position to camera position

src/states_screens/track_info_screen.cpp
High scores are now updated on init() and after change of number of AIs.
=> Fixed highscores update

src/scriptengine/script_engine.cpp
This fixes the crash when entering a level (issue #2214)
=> Fix flags on GetModule call

data/optimize_data.sh
This strips ICC headers from png files to silence warnings of newer libpngs:
```
[warn   ] Irrlicht: PNG warning: iCCP: known incorrect sRGB profile
[warn   ] Irrlicht: PNG warning: iCCP: profile 'Photoshop ICC profile': 'RGB ': RGB color space not permitted on grayscale PNG
```
Additionally the removal of this headers gains a bit more space :-).
=> Strip ICC headers from png files to silence warning

src/tracks/track_object_presentation.cpp
This fixes a crash when trying to load story mode with latest master.
=> Fix crash when loading story mode

src/states_screens/options_screen_audio.cpp, src/states_screens/options_screen_input.cpp, src/states_screens/options_screen_input2.cpp, src/states_screens/options_screen_ui.cpp, src/states_screens/options_screen_video.cpp, src/states_screens/user_screen.cpp
This fixes various issues reported by Coverity
=> Fix a couple of deref after NULL check in states_screens

data/shaders/pointemitter.vert, src/graphics/gpu_particles.cpp, src/graphics/gpu_particles.hpp, src/karts/kart.cpp, src/karts/kart_gfx.cpp, src/karts/kart_gfx.hpp
https://github.com/supertuxkart/stk-code/issues/1552
There is no more visual artifacts with nitro and skidding particles whatever the framerate.
=> Fix kart particles #1552

lib/irrlicht/include/utfwrapping.h, lib/irrlicht/source/Irrlicht/CGUIStaticText.cpp
Result:
Before any patch
Ugly hack and the final one
*I replace the text in po file as I don't know how to generate the box.
=> Fix the ugly hack for displaying Chinese in #2110, and then fix #2297

CMakeLists.txt, src/states_screens/main_menu_screen.cpp
This makes working on the network mode with git much easier
=> Allow enabeling Network Multiplayer through CMake flags

data/shaders/rhpassthrough.geom
https://github.com/supertuxkart/stk-code/issues/2328
=> Fix global illumination bug with intel driver #2328

src/network/protocols/get_public_address.cpp, src/network/protocols/get_public_address.hpp, src/states_screens/main_menu_screen.cpp
This PR mainly consists of refactoring and documenting, but it also ensure that a new STUN request is send and an error message is printed every time a response contained invalid data.
=> Added documentation, refactored large code pieces and implemented a consitent error handling for the STUN requests

src/physics/physical_object.cpp
There are a few other things in there that make me wonder whether you use a custom operator new or Boehm GC or something, but I could not find any information. For example, pretty much all Dialog classes are just dynamically allocated but never deleted anywhere. Any ideas?
=> Fix a couple of memory leaks.

lib/irrlicht/CMakeLists.txt, lib/irrlicht/source/Irrlicht/CParticleMeshEmitter.cpp, lib/irrlicht/source/Irrlicht/CParticleMeshEmitter.h, lib/irrlicht/source/Irrlicht/CParticlePointEmitter.cpp, lib/irrlicht/source/Irrlicht/CParticlePointEmitter.h, src/graphics/post_processing.cpp, src/physics/btKart.cpp, src/race/history.cpp, src/scriptengine/script_challenges.cpp
-Wunused-variable for gcc and clang, and some only for clang.
=> Fixes few warnings at compilation

lib/irrlicht/include/IrrCompileConfig.h, lib/irrlicht/source/Irrlicht/CAttributeImpl.h, lib/irrlicht/source/Irrlicht/CIrrDeviceLinux.cpp, lib/irrlicht/source/Irrlicht/CIrrDeviceSDL.cpp, lib/irrlicht/source/Irrlicht/COSOperator.cpp, lib/irrlicht/source/Irrlicht/os.cpp
redo my previous pull request better.
=> better alternative OSes handling + tiny C++ fix

src/audio/sfx_manager.cpp
=> Add missing unlock

data/supertuxkart.appdata.xml
Closes https://github.com/supertuxkart/stk-code/issues/1545.
=> Update screenshots and description

INSTALL.md
A few more packages were needed.
=> Fix dependencies list for Ubuntu compilation

src/main.cpp
This closes #2092. User configuration options can be done in the command line.
=> Toggle graphical options from command line

src/modes/linear_world.hpp, src/states_screens/race_result_gui.cpp, src/states_screens/race_result_gui.hpp
Best lap time, difficulty and number of laps are displayed. This closes #1805. `linear_world.hpp` was edited to add an accessor for `m_fastest_lap`.
=> More information in race result GUI

.travis.yml
(and put them in alphabetical order.)
=> Update deps from INSTALL.md

src/karts/kart.cpp
#34 seems abandoned, this is (hopefully) the first in a series of PRs to get the same functionality, as #34 has merge conflicts.
=> Show boost at startup

data/gui/addons_screen.stkgui, src/states_screens/addons_screen.cpp, src/states_screens/addons_screen.hpp
This commit is for closing issue #1763 .
In the addons screen, remember if the Internet connection is disabled.
=> In the addons screen, remember that the Internet connection is disabled 

src/modes/world.cpp
I know this is a very minor typo. I just saw it while looking through the source code and thought I might as well make a pull request and fix it.
=> Fix CPU marker typo

src/audio/music_ogg.cpp, src/challenges/challenge_data.cpp, src/graphics/irr_driver.cpp, src/graphics/render_geometry.cpp, src/graphics/shadow_matrices.cpp, src/graphics/stk_scene_manager.cpp, src/guiengine/event_handler.cpp, src/guiengine/skin.cpp, src/guiengine/widgets/CGUIEditBox.cpp, src/guiengine/widgets/dynamic_ribbon_widget.cpp, src/input/wiimote_manager.cpp, src/karts/controller/end_controller.cpp, src/karts/controller/skidding_ai.cpp, src/karts/controller/test_ai.cpp, src/karts/kart_model.cpp, src/karts/skidding.cpp, src/main.cpp, src/online/online_player_profile.cpp, src/scriptengine/script_engine.cpp, src/scriptengine/scriptarray.cpp, src/states_screens/credits.cpp, src/states_screens/edit_track_screen.cpp, src/states_screens/kart_selection.cpp, src/states_screens/options_screen_device.cpp, src/states_screens/server_selection.cpp, src/tracks/check_line.cpp
See #2613
Edit: I did not change any of the networking code to avoid long merging headache to @hiker.
=> Fixes warnings

data/gui/help1.stkgui, data/gui/help2.stkgui, data/gui/help3.stkgui, data/gui/help4.stkgui, data/gui/help5.stkgui, sources.cmake, src/states_screens/help_screen_1.cpp, src/states_screens/help_screen_2.cpp, src/states_screens/help_screen_4.cpp, src/states_screens/help_screen_5.cpp, src/states_screens/help_screen_5.hpp
This closes #2174. More information could still be added and the GUI could also be improved to look better.
=> Add help page for banana penalties

src/main_loop.cpp
Smoother, see https://github.com/supertuxkart/stk-code/issues/2302.
=> Set menu FPS to 60

.appveyor.yml, tools/appveyor-irc-notify.py
with the script from battle of wesnoth team
https://raw.githubusercontent.com/wesnoth/wesnoth/master/utils/appveyor/irc-notify.py
=> Add irc notifications to appveyor

README.md
Also modify the travis badge to be an SVG instead of a PNG.
See my [repository](https://github.com/leyyin/stk-code/#supertuxkart) to see how it looks.
=> Add appveyor and freenode chat badges to README

src/main.cpp
lol `N=1 novice, N=2 driver, N=3 racer.`
=> Clean up output

CMakeLists.txt
=> Avoid error when libopenglrecorder not found

src/states_screens/grand_prix_win.cpp, src/states_screens/grand_prix_win.hpp
This is V1, I might make a modified version soon.
[winGP-new.zip](https://github.com/supertuxkart/stk-code/files/1116605/winGP-new.zip)
=> Add new GPwin cutscene

cmake/Toolchain-mingw-64bit.cmake, cmake/Toolchain-mingw.cmake
=> Fix MinGW cross-compilation

ISSUE_TEMPLATE.md
=> Add a github issue template to the project

README.md
Corrections:
* Dependencies
* aforementioned
=> README.md:correct spelling of 2 words [skip ci]

tools/ai_test/test_track.sh
=> Update the AI testing track list and reorder it to alphabetic order

INSTALL.md
Thanks @OzoneOne for testing this.
=> Update macOS instructions

src/guiengine/event_handler.cpp, src/guiengine/skin.cpp, src/guiengine/widgets/spinner_widget.cpp, src/guiengine/widgets/spinner_widget.hpp
Avoids the spinner blocking left/right navigation, which solves issues in some menus like the addons screen where you previously couldn't reach some part of the UI with the keyboard.
=> Improved spinner

data/gui/help7.stkgui
I think its called multiplayer in the main menu without race.
=> Change multiplayer race to multiplayer

data/gui/track_info.stkgui, src/race/highscores.hpp, src/states_screens/race_result_gui.cpp, src/states_screens/track_info_screen.cpp, src/states_screens/track_info_screen.hpp
The PR contains a few updates to the UI code to display it correctly
=> Change highscore limit from 3 to 5

src/main.cpp
This will allow for deterministic runs with the profiling options.
=> Add CLI option for setting random seed

src/karts/controller/local_player_controller.cpp
See https://github.com/supertuxkart/stk-code/issues/3550
=> Fix message

src/guiengine/widget.cpp, src/guiengine/widget.hpp
small improvements regarding widget collapsing
=> small improvements regarding widget collapsing

COPYING
See https://softwareengineering.stackexchange.com/questions/281949/how-to-properly-apply-a-license for why the the "How to Apply These Terms to Your New Programs" part was added.
The GPL was copy-pasted from https://www.gnu.org/licenses/gpl-3.0-standalone.html, but with some formatting changed to be like https://www.gnu.org/licenses/gpl.txt (only ASCII characters, etc.)
The top line is based on https://github.com/supertuxkart/stk-code/blob/master/src/main.cpp#L7
Note that Git shows a lot of changed lines because of the whitespace that got changed from the copy-paste.
=> Fix issues with COPYING (see desc.)

src/modes/linear_world.cpp, src/modes/linear_world.hpp, src/states_screens/race_result_gui.cpp
This shows who made the fastest lap in the race result screen.
=> Show the name of who made the fastest lap

src/main.cpp
It's more clear now that this is non-fatal.
=> Improve warning

data/supertuxkart.appdata.xml
Update description, using parts from https://supertuxkart.net/Discover.
=> Update description in supertuxkart.appdata.xml

data/supertuxkart.appdata.xml
=> Update description part 2

src/states_screens/options/options_screen_general.cpp
=> Disable internet-dependent checkboxes rather than hiding them

INSTALL.md, NETWORKING.md
Just added dependency instructions
=> Added documtation for CentOS/RHEL/Mageia/OpenSUSE

data/supertuxkart.appdata.xml
=> Description part 3

data/gui/screens/ghost_replay_selection.stkgui, data/gui/screens/online/profile_achievements_tab.stkgui, data/gui/screens/online/profile_friends.stkgui, data/gui/screens/online/profile_settings.stkgui, data/gui/screens/online/register.stkgui, data/gui/screens/tracks.stkgui, src/states_screens/addons_screen.cpp, src/states_screens/credits.cpp, src/states_screens/online/server_selection.cpp, src/states_screens/race_gui_base.cpp
=> GenIII for scaling issues fix

data/gui/dialogs/addons_loading.stkgui, data/gui/dialogs/confirm_resolution_dialog.stkgui, data/gui/dialogs/online/server_info_dialog.stkgui, data/gui/dialogs/online/user_info_dialog.stkgui, data/gui/screens/karts.stkgui, data/gui/screens/online/create_server.stkgui, data/gui/screens/tracks.stkgui, src/guiengine/widgets/kart_stats_widget.cpp, src/guiengine/widgets/skill_level_widget.cpp
This time they are for leaving enough space for fonts and making space depends on resolution.
=> UI fix bundle V

src/guiengine/skin.cpp, src/guiengine/widgets/kart_stats_widget.cpp, src/guiengine/widgets/player_kart_widget.cpp, src/guiengine/widgets/skill_level_widget.cpp
These are for multiplayer screen.
=> UI fix bundle VI

data/gui/dialogs/general_text_field_dialog.stkgui, src/states_screens/dialogs/general_text_field_dialog.cpp
=> Use icons in general_text_field

android/README.ANDROID, data/achievements.xml, data/kart_characteristics.xml, data/stk_config.xml, lib/irrlicht/include/EMaterialTypes.h, lib/irrlicht/include/ISkinnedMesh.h, lib/irrlicht/include/SIrrCreationParameters.h, lib/irrlicht/source/Irrlicht/CIrrDeviceWayland.cpp, lib/irrlicht/source/Irrlicht/CNullDriver.cpp, lib/irrlicht/source/Irrlicht/COGLES2Driver.h, lib/irrlicht/source/Irrlicht/COpenGLDriver.h, lib/irrlicht/source/Irrlicht/COpenGLParallaxMapRenderer.cpp, src/audio/sfx_openal.cpp, src/config/hardware_stats.cpp, src/config/user_config.hpp, src/graphics/graphics_restrictions.cpp, src/guiengine/event_handler.cpp, src/karts/kart.cpp, src/karts/max_speed.cpp, src/main.cpp, src/main_loop.cpp, src/network/network_string.hpp, src/network/protocol.cpp, src/network/protocol_manager.cpp, src/network/protocols/game_events_protocol.cpp, src/race/race_manager.cpp, src/states_screens/online/networking_lobby.cpp, src/tinygettext/language.hpp, src/tinygettext/po_parser.cpp, src/utils/translation.cpp
=> Fix several spelling/grammar errors

data/CREDITS, data/gui/dialogs/addons_loading.stkgui, data/gui/dialogs/android/init_android.stkgui, data/gui/dialogs/confirm_dialog.stkgui, data/gui/dialogs/debug_slider.stkgui, data/gui/dialogs/general_text_field_dialog.stkgui, data/gui/dialogs/ghost_replay_info_dialog.stkgui, data/gui/dialogs/online/achievement_progress_dialog.stkgui, data/gui/dialogs/online/change_password.stkgui, data/gui/dialogs/online/notification_dialog.stkgui, data/gui/dialogs/online/player_rankings_dialog.stkgui, data/gui/dialogs/online/recovery_info.stkgui, data/gui/dialogs/online/recovery_input.stkgui, data/gui/dialogs/online/registration_terms.stkgui, data/gui/dialogs/online/server_configuration_dialog.stkgui, data/gui/dialogs/online/splitscreen_player_dialog.stkgui, data/gui/dialogs/online/user_info_dialog.stkgui, data/gui/dialogs/online/vote_dialog.stkgui, data/gui/dialogs/press_a_key_dialog.stkgui, data/gui/dialogs/select_challenge.stkgui, data/gui/dialogs/select_challenge_nobest.stkgui, data/gui/screens/addons_screen.stkgui, data/gui/screens/feature_unlocked.stkgui, data/gui/screens/race_result.stkgui, src/states_screens/credits.cpp, src/states_screens/dialogs/debug_slider.cpp, src/states_screens/dialogs/ghost_replay_info_dialog.cpp, src/states_screens/dialogs/select_challenge.cpp, src/states_screens/edit_gp_screen.cpp, src/states_screens/race_gui_base.cpp
Sorry this time online editing since i used samuncle's rt branch (and i dont want to reset).
This time mostly dialogs
=> UI fix bundle VII

data/gui/dialogs/select_challenge.stkgui, data/gui/dialogs/select_challenge_nobest.stkgui, src/states_screens/dialogs/select_challenge.cpp
Please help me make some improvement first
=> New interface of challenge selection

data/gui/screens/options_ui.stkgui, src/config/user_config.hpp, src/font/font_with_face.cpp, src/guiengine/skin.cpp, src/main_android.cpp, src/states_screens/options/options_screen_ui.cpp
See title
If the pr is merged, please update .pot file
=> fix #3923 && replace fonts size to font size

data/gui/dialogs/addons_loading.stkgui, data/gui/dialogs/online/achievement_progress_dialog.stkgui, data/gui/dialogs/online/change_password.stkgui, data/gui/dialogs/online/network_ingame_dialog.stkgui, data/gui/dialogs/online/notification_dialog.stkgui, data/gui/dialogs/online/player_rankings_dialog.stkgui, data/gui/dialogs/online/recovery_input.stkgui, data/gui/dialogs/online/server_info_dialog.stkgui, data/gui/dialogs/online/user_info_dialog.stkgui, data/gui/dialogs/online/vote_dialog.stkgui, data/gui/dialogs/race_paused_dialog.stkgui, data/gui/dialogs/tutorial_message_dialog.stkgui, data/gui/screens/online/user_search.stkgui, data/gui/screens/race_setup.stkgui, data/gui/screens/user_screen.stkgui, data/gui/screens/user_screen_tab.stkgui
=> UI fix bundle IX

data/po/extract_strings_from_XML.py
=> Using xml.dom.minidom.parse is known to be vulnerable to XML attacks.

INSTALL.md
```
```
This pull request uses a single primary header, fixes lists, and indents code blocks inside lists to keep the list from restarting on certain markdown interpreters.
=> Fix format of INSTALL.md

src/states_screens/track_info_screen.cpp
I am so sorry that I forgot to fix this bug in previous PR#4063.
```
```
=> forgot to fix this bug in previous pr4063

data/gui/screens/track_info.stkgui, src/config/user_config.hpp, src/modes/world.cpp, src/race/race_manager.hpp, src/states_screens/track_info_screen.cpp, src/states_screens/track_info_screen.hpp
```
```
No1: Move red & blue AI num to race_manager
No2: Improve riso's code
No3: Give a bigger space in track info so that spinners won't be out-of-box
=> Some improvements for soccer AI spinner

data/gui/screens/race_result.stkgui, src/states_screens/race_result_gui.cpp
=> Icon button for race result

data/gui/screens/help1.stkgui, data/gui/screens/help2.stkgui, data/gui/screens/online/online.stkgui
=> resolution issue #4070 Wrong Icons

lib/irrlicht/source/Irrlicht/CIrrDeviceWayland.cpp
=> IrrDeviceWayland: Don't try to use non-existent wl_pointer object

android/make.sh
=> fix linking order: libpng before libz

src/main.cpp
modified:   src/main.cpp
```
```
=> Command-line help typo, fix

src/guiengine/widgets/kart_stats_widget.cpp, src/guiengine/widgets/skill_level_widget.cpp
=> Bigger kart stat

data/supertuxkart.appdata.xml
https://hughsie.github.io/oars/
```
```
=> Add OARS metadata

data/skins/coal/stkskin.xml, data/skins/forest/stkskin.xml, data/skins/ocean/stkskin.xml, data/skins/peach/stkskin.xml, data/skins/ruby/stkskin.xml
```
```
Several skin fixes.
It includes:
Give a small margin to spinner;
Fix #3953;
Fix #3752;
=> Various skin fixes

INSTALL.md
=> updated install instructions for windows

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md
=> Fixed some spelling mistakes

NETWORKING.md, src/network/server.cpp, src/network/server_config.cpp, src/network/server_config.hpp
=> Some small fixes

NETWORKING.md
=> Remove duplicate dependency for GUI-less binary build

data/gui/screens/addons_screen.stkgui, src/states_screens/addons_screen.cpp
=> Show only possessed checkbox in addons screen #3376

src/network/stk_ipv6.cpp
=> Missing header for network struct, vital for FreeBSD.

doc/supertuxkart.1, doc/supertuxkart.6
=> Man page fixes

INSTALL.md
Please, see https://en.opensuse.org/Help:Style#openSUSE_spelling
```
```
=> fix openSUSE name

.gitignore, src/guiengine/message_queue.cpp, src/guiengine/message_queue.hpp, src/race/race_manager.cpp, src/scriptengine/script_gui.cpp
This PR prepares the MessageQueue for Implementation in the Tutorial (#4187).
```
```
=> Adapting MessageQueue for Tutorial

src/online/link_helper.cpp
=> FreeBSD online linker URL support

lib/bullet/src/BulletCollision/CollisionShapes/btCompoundShape.cpp
=> bullet build warning fix replacing by C++ casting

lib/mcpp/main.c
=> mcpp dependency possible leak fix proposal

lib/irrlicht/source/Irrlicht/COctreeSceneNode.cpp, lib/mcpp/system.c, src/network/socket_address.hpp, src/network/stk_ipv6.cpp
=> FreeBSD build fix proposal.

src/utils/vs.hpp
=> FreeBSD thread name support.

src/audio/sfx_buffer.cpp, src/audio/sfx_buffer.hpp, src/graphics/stk_texture.cpp
=> slighty less C code proposal

data/po/extract_strings_from_XML.py, data/po/update_po_authors.py, tools/check_textures.py, tools/compute_client_error.py
=> Migration Python2 towards Python3

data/tips.xml
Mainly just grammar fixes and re-wording here.
```
```
=> Tweaks to tips

src/config/hardware_stats.cpp, src/utils/crash_reporting.cpp, src/utils/separate_process.cpp, src/utils/vs.hpp
=> NetBSD build few updates.

data/gui/dialogs/online/user_info_dialog.stkgui, src/states_screens/dialogs/network_player_dialog.cpp, src/states_screens/main_menu_screen.cpp, src/states_screens/online/tracks_screen.cpp
=> Fix display of some icons, misc. fixes

src/karts/kart.cpp
When spectating someone with a high latency, the sound was really annoying when using headphones. This seems to fix it. Thanks @Benau for telling me where to look.
```
```
=> Use smoothed position for kart sounds

data/supertuxkart.desktop
See http://www.hadess.net/2020/05/dual-gpu-support-launch-on-discrete-gpu.html for details.
```
```
=> Add PrefersNonDefaultGPU=true to .desktop

src/modes/soccer_world.cpp
Hi, once a goal is made in soccer, it will show who made the goal and if it is an own goa, see figures below. I also made a log of goals on servers. Hope you like it. 
```
```
=> Show a message once a goal is made in soccer

src/guiengine/widgets/list_widget.cpp
Use the color specified by the skin for the text in the player list.
```
```
=> Use skin color for player list

src/graphics/central_settings.cpp, src/graphics/central_settings.hpp, src/graphics/gl_headers.hpp
=> Add memory total for NVIDIA cards in the logs

lib/glew/src/glewinfo.c, src/utils/separate_process.cpp
=> Haiku glew build fix and update.

src/utils/vs.hpp
=> util/debug thread naming for haiku.

data/gui/screens/options_ui.stkgui
Also simplify the surrounding code a bit.
```
```
=> Fix "Custom" button padding in UI Options screen

src/online/link_helper.cpp
=> online helper enabled on haiku

src/tracks/terrain_info.cpp
=> fix spelling error

CMakeLists.txt, lib/angelscript/source/as_memory.cpp, src/utils/crash_reporting.cpp, src/utils/string_utils.cpp, src/utils/vs.hpp
=> DragonFlyBSD support, mainly FreeBSD codepath.

src/graphics/camera.cpp
There was a minor typo on line 71.
```
```
=> Fixed a typo in camera.cpp

src/graphics/camera.cpp, src/graphics/camera.hpp
=> Fix some more typos

src/online/link_helper.cpp
=> xdg-open NetBSD supports it too.

data/gui/dialogs/custom_camera_settings.stkgui, src/states_screens/dialogs/custom_camera_settings.cpp
Hi, here is the reset button :D
```
```
=> reset button on camera settings

src/utils/vs.hpp
=> OpenBSD utility build update.

INSTALL.md
Ubuntu is based on Debian :)
```
```
=> Change Ubuntu to Debian-based Distributions

src/utils/vs.hpp
=> debugging current thread id on apple too

.github/workflows/main.yml
Also includes content needed for macOS, but macOS builds are disabled because harfbuzz can't seem to install properly
```
```
@maths22 Since you have (indirectly) contributed too to this commit, I'd need you to say if you would agree to the above statement about dual-licensing.
=> Added GitHub actions worlkflow file for Linux

src/states_screens/main_menu_screen.cpp
=> Fix english

.github/workflows/main.yml
```
```
(As with the original PR, I license these changes under CC0 to the STK team and everyone else at all epochs)
=> Repaired GitHub actions workflow

lib/irrlicht/source/Irrlicht/CFileSystem.cpp, lib/irrlicht/source/Irrlicht/CMountPointReader.cpp, src/input/gamepad_config.cpp, src/input/input_manager.cpp, src/utils/debug.cpp
=> Switch fixes

data/po/en.po, sources.cmake, src/config/hardware_stats.hpp, src/config/user_config.hpp, src/io/rich_presence.cpp, src/io/rich_presence.hpp, src/main.cpp, src/main_loop.cpp, src/modes/world_status.cpp, src/modes/world_status.hpp, src/race/race_manager.cpp
=> Discord rich presence

src/io/rich_presence.cpp
=> RichPresence: return on doConnect even when disabled

src/io/rich_presence.cpp, src/io/rich_presence.hpp
=> RichPresence: support addon tracks and karts

src/main.cpp
insuring best performance.
```
```
=> Haiku graphics mode scheduler low latency rather power saving for

.github/workflows/switch.yml, switch/make.sh
=> Fix switch github actions cache

data/gui/dialogs/race_paused_dialog.stkgui, src/states_screens/dialogs/race_paused_dialog.cpp
=> Fixed issue #4243

src/input/input_manager.cpp, src/input/input_manager.hpp, src/input/sdl_controller.cpp, src/input/sdl_controller.hpp, src/items/attachment.cpp, src/items/flyable.cpp, src/karts/controller/controller.hpp, src/karts/controller/local_player_controller.cpp, src/karts/controller/local_player_controller.hpp, src/karts/kart.hpp
=> Rumble on collisions

src/states_screens/race_result_gui.cpp
=> Show survive time in three strikes battle

src/states_screens/race_result_gui.cpp
```
```
Adds feature from #4550
=> Show kart rank in race result screen

CMakeLists.txt
=> Fix Switch OpenAL

src/race/race_manager.cpp
```
```
In Follow the leader mode the greatest cumulated time is a better critera for deciding the rank if several karts have the same total of points. It was set to the less cumulated time as expected for the Grand Prix and Time Trial modes.
=> rank by greatest time if points equality in Follow the leader

src/race/grand_prix_data.cpp, src/race/grand_prix_data.hpp, src/states_screens/gp_info_screen.cpp, src/states_screens/tracks_and_gp_screen.cpp
=> Fix tracks not showing in grandprix info

src/states_screens/online/register_screen.cpp
=> Fix logout when changing local name

INSTALL.md
https://getsol.us https://distrowatch.com/table.php?distribution=solus
The package's name are generally the one stated in the README.md already, but they’re a couple of differences. Not that difficult to compensate searching for, but I did it anyway for others.
```
```
=> Added Solus dependencies commands

.github/workflows/apple.yml, .github/workflows/windows.yml
=> Fix apple and windows actions

INSTALL.md
I had previously suggested a pull request for it. However, the main issue with my original pull request was that it didn’t contain some packages I already had installed. So, I’ve corrected on misspelled package name, and added the remaining ones.
```
```
=> Update Solus dependencies.

src/states_screens/race_result_gui.cpp
=> Only save GP highscores for normal race and time trial

src/race/grand_prix_manager.hpp
=> Fix incorrect comment in grand_prix_manager.hpp

src/config/saved_grand_prix.cpp, src/config/saved_grand_prix.hpp, src/race/race_manager.cpp, src/race/race_manager.hpp, src/states_screens/dialogs/race_paused_dialog.cpp, src/states_screens/race_result_gui.cpp
=> Don't save highscore when player skipped track

src/modes/world.cpp, src/race/highscore_manager.cpp, src/race/highscore_manager.hpp, src/race/highscores.cpp, src/race/highscores.hpp, src/states_screens/gp_info_screen.cpp, src/states_screens/high_score_selection.cpp
=> Save minor mode in GP highscores

CHANGELOG.md
=> Fix my name

src/config/user_config.hpp, src/race/race_manager.cpp
=> Add a user config option to randomize the player position at the start

src/input/input_manager.cpp, src/input/sdl_controller.cpp, src/input/sdl_controller.hpp
Supposedly this already happened...
```
```
=> Drop support for SDL 1.x in SDLController

src/modes/world.cpp, src/race/highscore_manager.cpp, src/race/highscore_manager.hpp, src/race/highscores.cpp, src/race/highscores.hpp, src/race/race_manager.cpp, src/states_screens/gp_info_screen.cpp, src/states_screens/race_result_gui.cpp, src/states_screens/race_result_gui.hpp
=> Lap Trial improvements

data/po/ko.po, src/states_screens/online/register_screen.cpp
=> Revised email issue and some kr translation

src/network/protocols/server_lobby.cpp, src/network/protocols/server_lobby.hpp, src/network/server_config.cpp, src/network/server_config.hpp
=> Make limit of players in game configurable (#4685)

src/states_screens/online/networking_lobby.cpp, src/states_screens/online/networking_lobby.hpp
=> Soccer: Missing team changing button #4698

src/states_screens/race_result_gui.cpp
=> Add left side ghost replay difficulties

src/states_screens/online/register_screen.cpp
=> More precise error message for online unsername (2 & 3 from #3599)

src/states_screens/online/register_screen.cpp
=> Accept emails format like @e.email (from #4718)

src/items/item.cpp
Fixes bug where a bubblegum shield popping/bursting will leave an invisible gum object behind.
```
```
=> Improved code quality in item.cpp

src/states_screens/race_result_gui.cpp, src/states_screens/race_result_gui.hpp
=> Fix wrong lap count in GP result in Lap Trial mode

src/states_screens/race_result_gui.cpp
=> Fix assertion failed introduced in #4723

src/items/cake.cpp
Minor simplification while I am looking into how the cake logic might be improved when playing soccer.
```
```
=> m_gravity was set on the line above, so the condition will always be false

src/network/crypto_openssl.hpp, src/online/http_request.cpp, src/online/http_request.hpp
suppress openssl warning with openssl 3.0
```
```
=> http curl client favoured new progress api if supported.

src/io/file_manager.cpp, src/replay/replay_play.cpp, src/utils/mem_utils.hpp
trying out in two cases for now.
```
```
=> scoped deref mem utils intro proposal.

src/addons/addons_manager.cpp, src/audio/music_information.cpp, src/config/user_config.cpp, src/modes/easter_egg_hunt.cpp
=> widening a bit smart pointers usage considering xml data.

CMakeLists.txt, src/io/file_manager.cpp
original author @threedeyes slighty adapted.
```
```
=> upstreaming change for settings paths for haiku.

src/karts/controller/skidding_ai.cpp
=> BSD build warning little fixes, implicit cast.

src/utils/crash_reporting.cpp
Was going through old folders on my computer, wanted to get these changes merged so I can delete the old folders.
=> Tweaks to crash report dialog

src/karts/kart_properties_manager.hpp, src/states_screens/arenas_screen.cpp, src/states_screens/easter_egg_screen.cpp, src/states_screens/gp_info_screen.cpp, src/states_screens/kart_selection.cpp, src/states_screens/online/tracks_screen.cpp, src/states_screens/tracks_and_gp_screen.cpp
- Fix capitalization of "Standard" in kart and track selection screens
- Fix both "All" and "Standard" in random GP screen
- Code style/documentation/consistency improvements
```
```
=> Fix capitalization of categories, fixes #4622

lib/graphics_engine/include/vk_mem_alloc.h, lib/graphics_engine/src/ge_vulkan_command_loader.cpp, lib/graphics_engine/src/ge_vulkan_depth_texture.cpp, lib/graphics_engine/src/ge_vulkan_mesh_cache.cpp, lib/graphics_engine/src/ge_vulkan_skybox_renderer.cpp
=> gcc13 fixes

src/modes/world.cpp, src/modes/world.hpp
Reverts supertuxkart/stk-code#4861
Hiding the cursor was already implemented; one needs to make sure that Artist Debug mode is disabled.
=> Revert "Hide the cursor during gameplay"

data/gui/screens/options_general.stkgui
Fixes https://github.com/supertuxkart/stk-code/issues/4623
```
```
=> Clarify online chatting options

INSTALL.md
```
```
This punctuation was really confusing me so I made it more readable.
=> Clarify Shaderc Punctuation

src/font/digit_face.hpp, src/font/font_with_face.cpp, src/font/font_with_face.hpp, src/graphics/stk_text_billboard.cpp, src/guiengine/scalable_font.cpp
=> Fix #3471 v2

src/network/socket_address.cpp
=> make loopback checking more readable

src/graphics/draw_calls.cpp, src/graphics/lod_node.cpp, src/graphics/lod_node.hpp
```
```
Quick cull invisible LOD nodes & reduce dynamic_cast
=> Super mega LOD fix

src/race/grand_prix_data.cpp, src/race/grand_prix_data.hpp, src/race/race_manager.hpp, src/states_screens/grand_prix_cutscene.cpp
=> Fix #5053 (bool vector -> uint8_t vector)

src/challenges/story_mode_status.cpp
=> Fix #3671 & #4254 & #4925

CMakeLists.txt
based on patch from https://github.com/msys2/MINGW-packages/pull/20587 but without breaking changes
```
```
=> improve MinGW build

src/states_screens/online/online_profile_achievements.cpp
=> Center-align Goal and Progress columns on profile page

lib/irrlicht/source/Irrlicht/CGUIContextMenu.cpp, lib/irrlicht/source/Irrlicht/CIrrDeviceSDL.cpp, lib/irrlicht/source/Irrlicht/CMeshManipulator.cpp, lib/irrlicht/source/Irrlicht/CNullDriver.cpp, lib/irrlicht/source/Irrlicht/COSOperator.cpp, lib/irrlicht/source/Irrlicht/COSOperator.h, lib/irrlicht/source/Irrlicht/CSceneManager.cpp, lib/irrlicht/source/Irrlicht/os.cpp
Avoid dereferencing null pointer
Remove some unused variables
```
```
=> Fix some compiler warnings in irrlicht

INSTALL.md
=> Fix typos in `INSTALL.md`

lib/mojoal/mojoal.c
Upgraded mojoAL to version from current main branch, and it fixed #5188
```
```
=> Update mojoAL, fixes #5188

src/items/item.cpp, src/items/item.hpp
=> Avoid iterating appear animation node when it's invisible

.github/workflows/windows.yml
=> Fix Windows armv7 build

src/network/remote_kart_info.hpp
=> Add include to work with gcc15.

src/utils/debug.cpp
=> Change Anvil to Anchor and Bowling to Bowling ball in artist debug menu

data/shaders/IBL.frag, data/shaders/pointlight.frag, data/shaders/sp_grass_pass.vert, data/shaders/sp_pass.vert, data/shaders/sp_skinning.vert, data/shaders/sunlight.frag, data/shaders/sunlightshadow.frag, data/shaders/sunlightshadowpcss.frag, data/shaders/utils/DiffuseIBL.frag, src/graphics/lighting_passes.cpp, src/graphics/texture_shader.cpp, src/graphics/texture_shader.hpp
```
```
That's hell a lot of fix
Overworld assets needs to be updated
=> Shader Fix Bundle

src/network/protocols/server_lobby.cpp
=> Don't apply ranking 64 times

data/gui/screens/credits.stkgui, data/stk_config.xml, src/config/stk_config.cpp, src/config/stk_config.hpp, src/states_screens/credits.cpp
=> Add clickable link to stk website in credits page

lib/mojoal/LICENSE.txt, lib/mojoal/mojoal.c
```
```
I still think we should see if we can use OpenAL-Soft on macOS instead for the more advanced audio rendering, but at least audio is no longer very broken on macOS.
=> Update mojoAL to latest version, fixes #5418

src/guiengine/widgets/player_kart_widget.cpp, src/guiengine/widgets/player_kart_widget.hpp, src/guiengine/widgets/spinner_widget.cpp, src/guiengine/widgets/spinner_widget.hpp
=> Stk 1.5/game master in splitscreen 5352
