supertuxkart/stk-code

data/po/update_pot.sh, src/online/online_player_profile.cpp, src/tinygettext/plural_forms.cpp, src/utils/translation.cpp, src/utils/translation.hpp
Support plural translations by implementing a variant of ngettext with slightly different parameters (similar to the gettext() variant).
Also add Gaelic plural forms to tinygettext. (from https://github.com/leper/tinygettext/commit/d3cc412ab1d645d97c603991caf7fb9669224fcf)
=> Support plural translations. Fixes #1852.

src/states_screens/user_screen.cpp
This fixes the issue that textfields and checkboxes were only updated if you clicked on the user. When the screen was opened in the tabbed version they weren't initialized because the focus was swapped in `selectUser`.
I changed it so the focus is only set in the non-tabbed-screen, but the rest gets initialized in the tabbed version too.
=> Update checkboxes and textfield in the tabbed user screen too

src/tracks/track_manager.cpp
Populate irrlicht's texture cache on startup with all the track
screenshots to avoid the problem
This fixes issue #1892
=> Fix music stop problem when loading track selection screen

data/gui/addons_screen.stkgui
As the title says, here's how it currently looks like on low resolutions like 800x600. (1024x768 is also a problem). I changed the proportion and now it looks great on low resolutions and still looks great on high resolutions.
=> Make note spinner values of addons search bar readable in low resolution

src/main.cpp, src/online/http_request.cpp, src/online/request.cpp, src/online/request_manager.cpp, src/online/request_manager.hpp
When executing a request there was no check to see if is abortable, only the request manager was consulted in this regard, ignoring the option to the individual requests.
=> Fix sending of 'client-quit' request on quit. Also fix abortable requests.

src/states_screens/race_result_gui.cpp
This pull request should improve the layout of the race result screen. It fixes  #1767 and the highscore list looks better at tiny resolutions.
=> Improve the layout of the race result screen

src/modes/linear_world.cpp
Only the top half of the last lap message was displayed when SuperTuxKart was compiled with clang (version 3.5.1), the bottom half was an empty string. @hiker found out that clang deletes the string too fast, so caching it as a local variable fixes that problem.
=> Fix clang build, freeing memory too early

src/karts/kart.cpp, src/main.cpp, src/modes/world_status.cpp
* I must have forgotten to add brackets there. It shouldn't have much impact, but it still looks better with brackets
* The bigger part of this pull request starts sound and music when stk is started with '-R' and the ready-set-go-phase is skipped. I can do most of the initialization in the `reset()` function but starting the music there doesn't work so I moved it to the `MUSIC_PHASE` which also adds the music author at the bottom of the screen. The only functional change I made is setting `m_race_now` to false after that's done, so if another race is started afterwards the read-set-go-phase isn't skipped.
=> Fix music and sound when starting with -R and add brackets to a calculation

src/karts/kart.cpp, src/karts/kart.hpp, src/karts/skidding.cpp
I added two lights when skidding, one yellow for the first level and one red for the second.
This implements the idea that Arthur-D mentioned in #1724.
=> Add light effect when skidding

src/main.cpp
Starting stk with `--no-graphics` crashed because it tried to query the GraphicsRestrictions.
=> Fix crash with --nographics

src/audio/music.hpp, src/audio/music_dummy.hpp, src/audio/music_information.cpp, src/audio/music_ogg.cpp, src/audio/music_ogg.hpp, src/audio/sfx_manager.cpp
This patch removes the updateFading method because it doesn't do the right thing. `updateFading` sets an absolute volume but the fading last lap music should have a relative volume compared to the maximum. That's exactly what `setVolume` does so I used that instead.
The last lap music works for me with this patch, but probably (I'm not sure) samuncle's and 
Odd0002's issues aren't related to this.
=> Set correct volume for last lap music

.gitignore, src/online/xml_request.cpp
Ideally this should be properly done for each API call and to check if it was a success.
But for now, this works as well, it's very useful for development purposes, especially for me :).
=> Add logging for API requests that are not successful.

src/guiengine/widgets/dynamic_ribbon_widget.cpp, src/guiengine/widgets/dynamic_ribbon_widget.hpp, src/states_screens/options_screen_video.cpp
With this change, the resolutions in the options screen are sorted by their size, so the greatest resolution is on the right and the lowest on the left.
=> Sort resolutions by size

data/shaders/colortexturedquad.frag, src/guiengine/scalable_font.cpp
This patch fixes transparency of fallback characters in title fonts.
The brackets in the credit screen didn't fade out and in which was caused by the shader that didn't respect transparency (I hope this isn't expected behaviour)
and the colors that didn't change because they were static.
Additionally I changed the order of yellow and orange, so it fades from yellow to orange now.
=> Fix transparency of fallback characters

src/graphics/camera.cpp, src/graphics/camera.hpp, src/input/input_manager.cpp, src/input/input_manager.hpp, src/utils/debug.cpp
This pull request contains two improvements/changes for the fps camera:
* I changed the way, how the mouse position is handled: There is now a limit for the movement per event, that works better than ignoring a number of events.
* I added a new "mode" for the first person camera, that attaches it to a kart. That allows to drive a kart from a different (fixed) position than normal.
=> Improvements for the first person camera

src/addons/addons_manager.cpp, src/config/hardware_stats.cpp
This are two commits of #1907:
* leyyin found out that some stats were sent in `reportHardwareStats()` and in `getGLLimits(&json)`. Completing the getGLLimits method will introduce the same problem with e. g. GL_SHADING_LANGUAGE_VERSION
* The addon-server which is written into the addons_installed.xml now gets extracted from the UserConfig
=> Fix two issues related to the addon server

src/graphics/camera.cpp, src/input/input_manager.cpp, src/utils/debug.cpp
* The camera can be moved up and down with the `r` and `f` key
* The rotation is reset when the fps camera gets activated (fixes #2040)
* The rotation code changed a bit, the camera shouldn't be stuck at high angles anymore (like mentioned in #2040)
=> A few extensions and fixes for the first person camera

src/graphics/camera.cpp, src/graphics/camera.hpp, src/graphics/irr_driver.hpp, src/graphics/post_processing.cpp, src/graphics/render.cpp
Motion blur wasn't working right in multiplayer because it relied on a matrix from the previous frame, which was saved globally.
Storing that matrix camera dependent solves this issue.
It fixes #1937.
=> Fix motion blur in multiplayer

src/utils/translation.cpp
Fribidize crashed when strings in RTL languages exceeded 512 chars length.
I tested this code on Windows but not on linux where the string shouldn't be copied.
=> Allocate memory dynamically in fribidize

src/achievements/achievement.cpp, src/challenges/challenge_data.cpp, src/graphics/irr_driver.cpp, src/graphics/stk_text_billboard.cpp, src/input/input_manager.cpp, src/modes/world.cpp, src/states_screens/dialogs/select_challenge.cpp, src/states_screens/edit_gp_screen.cpp, src/states_screens/edit_track_screen.cpp, src/states_screens/gp_info_screen.cpp, src/states_screens/grand_prix_editor_screen.cpp, src/states_screens/race_gui_overworld.cpp, src/states_screens/track_info_screen.cpp, src/tracks/track.cpp, src/utils/translation.cpp
I fixed some issues with RTL languages and removed some unnecessary code.
There were some missing `fribidize` invocations and I changed the position the track/gp-name to the right side of the screen to avoid issues with long names.
There's a new debug option to force text to be right-to-left in `translations.cpp`.
Edit: I forgot to mention that this pull request depends on the changes I made in  #2057 (Allocate memory dynamically in fribidize).
=> Fix some issues with RTL languages

src/graphics/gl_headers.hpp
This fixes this warning:
supertuxkart/stk-code/src/graphics/gl_headers.hpp:16:17: warning: 
'glVertexAttribDivisor' macro redefined
^
supertuxkart/stk-code/lib/glew/include/GL/glew.h:2382:9: note: 
previous definition is here
#define glVertexAttribDivisor GLEW_GET_FUN(__glewVertexAttribDivisor)
^
=> Fix glVertexAttribDivisor redefinition warning

src/utils/translation.cpp
I hope this fixes (finally) #1823.
=> Mark text as RTL when at least one character is RTL

src/main.cpp
Moving output modifier and early exit options (--help, --version,
--log, etc) earlier in the execution so nothing useless is printed.
English is not my native language and I have to admit, I hesitated a moment about the function name. Tell me if its not clear enough.
=> Fix #2102.

src/utils/translation.cpp
Last commits introducing some new functions for fribidi didnt have preprocessor conditions, this lead to a break in compilation without fribidi.
=> Fix compilation with -DUSE_FRIBIDI=0

src/achievements/achievement_info.hpp, src/guiengine/widgets/bubble_widget.cpp, src/guiengine/widgets/player_kart_widget.cpp, src/race/grand_prix_data.hpp, src/states_screens/grand_prix_editor_screen.cpp, src/states_screens/online_profile_achievements.cpp, src/utils/translation.cpp, src/utils/translation.hpp
I hope I didn't mix up too many unrelated changes here. There are some little changes that
- fix #2125,
- the second part of #2132 (“Please select a Grand Prix”),
- the achievement display (@GreenLunar mentioned it in #1815),
- use isRTLText instead of isRTLLanguage in the BubbleWidget (if text is untranslated) and
- I partially fixed the TEST_BIDI debug option (it's still not working when you try to choose a kart in multiplayer).
The bigger change (fae12f3) is to fix a bidi issue in the multiplayer KartSelection screen where a multiline string (with `\n`) should be displayed. That caused issues with fribidi so now the text is splitted into lines before it gets fribidized.
Update: TEST_BIDI works in the multiplayer kart-selection screen now
=> Fix some translation and bidi issues

data/po/update_pot.sh
Here’s a patch to remove the sorting of the strings for translation. Currently, they’re sorted alphabetically, which makes translation more difficult and error-prone, since one can’t see the strings in proper context (e.g., the strings ‘Ready!’, ‘Set!’ and ‘Go!’ appear in completely different parts of the translation file). After applying the patch, the strings will appear in ‘natural’ order, i.e., in the source code order.
=> Don’t sort strings alphabetically (makes the translators’ work much easier)

data/po/supertuxkart.pot, src/states_screens/register_screen.cpp
Also, i raised the min value to 5 since as i explained in the issue thread, we might want to be ready for a 1 character tld.
=> Fix #2164 : Resized max length of mail address up to 254 chars

src/states_screens/dialogs/addons_loading.cpp
The string was reversed twice. This fixes #2226.
=> Fix reversed rtl string part

src/graphics/lod_node.cpp
As vlj uses separate cameras for the shadows, the LoD nodes can take the camera position now (fixes #1742).
=> Use camera position for LoD instead of the kart position, fixes #1742

src/states_screens/race_result_gui.cpp
This fixes #2041: The scoreboard ignored the first place in follow-the-leader but it takes a while until the race ends when only one player is left. In this time it is possible to overtake the leader, so the wrong player was ignored.
=> Properly ignore the leader in the ftl scoreboard

src/states_screens/cutscene_gui.cpp
Some window managers don't honour window size requests. If the window is bigger than requested, only the top left corner of cutscenes will fade.
=> Check size of window; don't assume it equals requested size

src/karts/kart.cpp, src/karts/kart.hpp
https://github.com/supertuxkart/stk-code/issues/2182
I added some SFX to nitro. Beside the changes in the code, some changes have to be done in stk_assets :
- adding http://www.bigsoundbank.com/dl.php?ext=ogg&id=0851 in stk-assets/sfx/ and renaming it nitro.ogg
- adding the following line to stk-assets/sfx/sfx.xml :   
`<sfx filename="nitro.ogg"            volume="3.0" positional="true" rolloff="0.5" />`
The result can be seen here : https://youtu.be/fU1IYIvejnw?t=46s
=> Added SFX to nitro

lib/irrlicht/include/utfwrapping.h
Correct comment of namespace
The quotation added is for Chinese Simplified, which I discovered usage in translation work, to display better.
Sorry for extra pull
=> Fix typo and and add quotation

src/karts/controller/player_controller.cpp
https://github.com/supertuxkart/stk-code/issues/2232
Moving the camera "manager" before the penalty time check allows the player to look backward during the countdown.
=> Offers the possibility to look backward during the start phase. #2232

src/states_screens/race_setup_screen.cpp
If the race setup screen is entered while the SuperTux difficulty is unavailable (locked), the SuperTux difficulty button will retain its locked badge and inactive state forever -- that is even if said difficulty becomes available (e.g. by changing the current user).
=> Fix SuperTux difficulty button state not updating correctly

data/po/update_pot.sh
This patch changes the string extraction so that strings aren’t sorted alphabetically. This makes the translators’ work *much* easier. (For more information, see previous pull request #2188, which was applied, but whose effect was accidently removed by a later commit.)
=> Don’t sort strings alphabetically (again)

cmake/FindAngelscript.cmake
Upstream names the shared library angelscript_s.
In addition, add more common PATH_SUFFIXES.
=> Fix compilation with system angelscript

src/graphics/shader.cpp
I tried to fix shader compilation with some drivers:
http://forum.freegamedev.net/viewtopic.php?f=17&t=6600
I don't know if it will work since I can't reproduce the issue described in this topic. According to GLSL specification, precision qualifer are useless with OpenGL (they only have an effect with OpenGL ES), so this PR should not break anything, at worse it is useless.
=> Add default precision qualifier in fragment shaders

data/stk_config.xml, src/config/stk_config.cpp, src/config/stk_config.hpp, src/guiengine/ft_environment.cpp, src/guiengine/scalable_font.cpp, src/guiengine/scalable_font.hpp
Extract from my old freetype issue:
2.Change title font color according to skin
As they are color-able now, it would be good to make them match the skin.
3.Configurable font for experts?
Allowing overwritten the default font config, ie custom font, can be done on command line side.
-----
Now I finished no.3, which @leyyin suggests, by not (and shouldn't anyway) hard-coding font file names in source. I warned users too about the risks of changing font themselves already.
I also remove some unused header and coding style fixing in scalable_font src (NOT tested in windows).
I think I should be able to handle no.2 too (if stk devs think it's good idea to make a "smart" title font color, like the screenshot), I can implement that in this custom_font branch, and keep this PR open.
=> Allow configurable fonts file names in stk-config

INSTALL.md, README.md
* added space after `#` headline
* corrected file names of files I could find
* linked to files
However one thing I could not fix was this sentence:
"Information about the licenses for artwork are contained in 
`data/licenses`."
The mentioned file or dir does not exist (anymore) and I could not find any other file, which would fit there.
=> Readme and Install.md improvments

lib/bullet/src/BulletCollision/CollisionDispatch/btCollisionObject.h, lib/bullet/src/BulletDynamics/Dynamics/btRigidBody.cpp, lib/bullet/src/BulletDynamics/Dynamics/btRigidBody.h, src/animations/animation_base.cpp, src/animations/ipo.cpp, src/animations/three_d_animation.cpp, src/audio/sfx_openal.cpp, src/graphics/camera.cpp, src/graphics/material.cpp, src/items/flyable.cpp, src/items/rubber_ball.cpp, src/karts/controller/skidding_ai.cpp, src/karts/kart.cpp, src/physics/kart_motion_state.hpp
Replaced instances of \<math.h\> with \<cmath\>, and replaced all instances of isnan() with std::isnan(). This fixes the debug build on GCC 5.3.0. 
Requires testing on Windows and Mac.
=> Fix debug build on GCC 5.3.0

src/modes/cutscene_world.cpp, src/modes/world_status.cpp, src/modes/world_status.hpp
I've added a user config entry for disabling the sound at race start. This is useful when you're listening to some music on your PC and don't want it to clash acoustically with the race start sounds.
=> Support disabling race intro sound

src/network/protocols/server_lobby_room_protocol.cpp
Triggers a weird 9 year old RPM bug when extracting debugging information for the compiled binary:
https://bugzilla.redhat.com/show_bug.cgi?id=304121
=> Fix double slash in include

data/graphical_restrictions.xml
See https://github.com/supertuxkart/stk-code/issues/2521.
=> Fix warning for cards without "Radeon" in string

lib/irrlicht/CMakeLists.txt, lib/irrlicht/source/Irrlicht/CImageLoaderJPG.cpp
Issues found while adding stk as a package for Buildroot, which allows playing it on embedded x86 platforms such as the Minnowboard family.
See https://patchwork.ozlabs.org/patch/634103/
=> Minor fixes for issues found while cross-building v2

src/input/wiimote_manager.cpp
There was a missing space in a string for the wiimote manager.
=> Add missing space in string for wiimote manager

data/gui/confirm_dialog.stkgui, src/states_screens/dialogs/message_dialog.cpp, src/states_screens/dialogs/message_dialog.hpp
When you start SuperTuxKart for the first time the buttons will now be next to each other horizontally.
=> Place buttons in confirm dialog horizontally

src/main_loop.cpp
This patch changes audia to audio in the source code of src/main_loop.cpp.
=> Fix typo in main_loop.cpp

src/karts/kart.cpp
A few of the include statements in `kart.cpp` were written twice. It looks like `kart.cpp` is the only file with obvious redundant include statements like this.
=> Remove duplicate include statements from kart.cpp

lib/irrlicht/source/Irrlicht/os.cpp
Tested for NetBSD, the same signature has DragonFly(http://fxr.watson.org/fxr/source/sys/endian.h?v=DFBSD#L42)
=> Add a little more BSD support

.appveyor.yml
Only x86 VS 2015
No notification, probably best for the first uses.
All you need to do to start using the appveyor CI is to create an account and link the GH repo to it, and select branches or PR to be built.
See #2649 for the rest of the discussion
=> Adding appveyor config file

lib/irrlicht/source/Irrlicht/MacOSX/CIrrDeviceMacOSX.mm
The compiler error I got was:
`
lib/irrlicht/source/Irrlicht/MacOSX/CIrrDeviceMacOSX.mm:722:44: error: cannot initialize a parameter of type 'id<NSFileManagerDelegate> _Nullable' with an rvalue of type
'id<NSApplicationDelegate> _Nullable'
`
=> Fix compilation on macOS 10.12

src/graphics/slip_stream.cpp
Slipstreams will no longer be created by or effect ghost karts because ghost karts should not have any effect on other karts.
=> No slipstream from ghost kart, fix #2721

src/utils/time.hpp
Hi, this is some very minor change but it fixes a compilation bug when using this configuration :
```
CC=clang CXX=clang++ \
CFLAGS="${CFLAGS} -flto=thin" \
CXXFLAGS="${CXXFLAGS} -flto=thin"\
LDFLAGS="${LDFLAGS} -flto=thin" \
cmake -D_CMAKE_TOOLCHAIN_PREFIX=llvm- \
-DUSE_FRIBIDI=0 -DUSE_WIIUSE=0 -DCMAKE_BUILD_TYPE=Debug ..
```
The linker used was ld.gold and I had to increase my tmpfs used by clang from ~750MB to ~1GB for all the objects to be stored during link time.
=> Fix clang compilation

src/states_screens/soccer_setup_screen.cpp, src/states_screens/soccer_setup_screen.hpp
The target amount of goals was not initialized for a soccer game if the player pressed fire and not continue.
This fixes #2769.
=> Fix sometimes not initializing a soccer game

data/stk_config.xml, src/config/stk_config.cpp
New GP point system as discussed on the IRC with @auriamg & @Arthur-D.
Compiled & tested.
It adds a compilation warning about a comparison between an unsigned int and a signed int. It shouldn't have any consequence, and I'm not sure how to solve the warning. For info, it's on the line 227 of the .cpp.
Tested, and everything works. The point are attributed correctly according to what is in the config, it also tolerates the case where there is more karts than points nodes (it defaults to a zero difference for the supernumerary karts, but the config supports up to 30 before defaulting to it).
I used my own formula for the scoring, but the new system is more powerful - even if one would prefer to tweak the specifics differently, he would have more options.
Commit fixing #1699
=> New GP point system

README.md
No such system stylized as "macOS X."
Left "OS X Install" because I don't think Apple uses install DVD's anymore since renaming as macOS?
=> Changed "macOS X" to "macOS"

src/main.cpp
This was a complaint of Michael Larabel from Phoronix and is why he doesn't use STK in benchmarks; because the new tracks are mostly locked from the start and unavailable even with the --track flag. I'm looking into updating the test profile on OpenBenchmarking.org and hopefully this will lead to some new visibility if Michael benchmarks STK.
=> Add option to unlock everything with a command line flag

src/main.cpp
If the menu is shown, there's this ugly purple background (the OpenGL default, I think) and the cutscene won't play. It doesn't make sense to show the menu anyway if the user wants to immediately play a cutscene.
=> Fix the --cutscene=<cutscene> commandline flag

src/karts/controller/controller.cpp, src/karts/controller/controller.hpp, src/karts/controller/ghost_controller.cpp, src/karts/controller/ghost_controller.hpp, src/replay/replay_base.hpp, src/replay/replay_play.cpp, src/replay/replay_play.hpp, src/replay/replay_recorder.cpp, src/states_screens/ghost_replay_selection.cpp, src/states_screens/race_result_gui.cpp, src/states_screens/race_result_gui.hpp
Fixes #2754.
* Store usernames of each racer in recorded replay files
* Display those usernames in a column of the replay selection UI
and in race result dialogs
* If an older replay file is used that does not have usernames, kart name is displayed in race result dialogs (which is the current behavior)
* RaceResultGUI::getKartDisplayName functionality moved into
Controller::getName
=> Save and use usernames in replay files (#2754)

src/config/user_config.hpp
Older version's "false" in the config file translates to "0", which disables all particles in 0.9.3.  Mitigate this by renaming the config name.
See https://forum.freegamedev.net/viewtopic.php?f=17&t=7662&sid=71b18d47f0b9d436d4bd17c2da8cbb86#p74823 for an example of this causing confusion.
=> Prevent upgrades to 0.9.3 causing all particles to be disabled

src/states_screens/race_gui_overworld.cpp
Keep the "fortmagma" challenge marked as locked on the GUI minimap even if enough points (180+) have been gathered to unlocked it, when the door is not open yet.
This tiny change make things way less confusing than having the final track "unlocked" and arriving at the door to be told that it is, in fact, not available yet.
=> Mark "fortmagma" as locked on the minimap until the door can open

lib/glew/CMakeLists.txt, lib/glew/include/GL/eglew.h, lib/glew/include/GL/glew.h, lib/glew/include/GL/glxew.h, lib/glew/include/GL/wglew.h, lib/glew/src/glew.c, lib/glew/src/glewinfo.c
Previous version was a modified GLEW 1.11.0 (2014). The STK modifications meant
to address https://sourceforge.net/p/glew/patches/40/ which is now fixed since
GLEW 2.0.0.
I've tested that it builds fine on Linux (Mageia 6 x86_64), though I haven't tried running STK itself with these changes as I did not checkout the assets. It should likely be tested on Windows before merging to make sure that it builds out of the box (*Edit:* Ah well, AppVeyor will make sure of that).
---
For the reference, here's the diff between pristine 1.11.0 and STK's version before this patch:
```diff
diff --git a/lib/glew/src/glew.c b/lib/glew/src/glew.c
index a78f14e1e..f8df0d758 100644
--- a/lib/glew/src/glew.c
+++ b/lib/glew/src/glew.c
@@ -296,30 +296,6 @@ static GLboolean _glewStrSame3 (GLubyte** a, GLuint* …
```
=> GLEW: Update to pristine upstream 2.1.0

src/modes/linear_world.cpp
This change fixes the issue #3126 that I opened. From a player standpoint, I disagree with having the message "Final lap!" appear when starting a one-lap race. This change makes the "Final lap!" message only appear in races that have more than one lap.
=> Remove "Final lap!" message in one-lap races

src/utils/debug.cpp
It supports doing so either by key shortcut (ctrl+F5/F6) or by new menu options (the key shortcuts are also indicated there).
The code checks what is the index of the kart to which the active camera look at ; so mixing some inputs by key shortcuts and by menu options works. In the same way, if the menu options are used to set the active view to one of the eight first kart, the previous/next options will automatically pick it up.
=> Change camera view in debug to the previous/next kart

data/stk_config.xml
Revisiting my contribution from last year, I've improved the GP points distribution.
The improvements are twofold : 
- Better reward victory and the places close after ; as the previous distribution wasn't aggressive enough, especially with a lot of karts.
- Smooth significantly the point rewards
This is with the old distribution : 
This is with the new one : 
The total of points distributed don't increase too much (especially with 20 karts or less : 10 karts : the 1st get from 16 to 18; 15 karts : 28->30 ; 20 karts : 39->50) ; as the additional high value nodes are compensated by less middle-value nodes ; so the player won't be confronted with excessive numbers.
=> Better GP points distribution

CMakeLists.txt, data/CREDITS, src/states_screens/credits.cpp, src/utils/constants.cpp, src/utils/string_utils.cpp, src/utils/string_utils.hpp
Just greasing the wheels of the releasing process a little bit. :)  ~Note that std::regex_replace is cpp11~ (no longer needed).
=> Reduce number of places version number needs to be changed on release

src/guiengine/event_handler.cpp, src/guiengine/widgets/ribbon_widget.cpp, src/guiengine/widgets/ribbon_widget.hpp
This PR contains a few keyboard/gamepad navigation improvements : 
- Don't focus empty lists/empty ribbons (nothing indicates that the empty element is focused ant that's confusing)
- Ignore deactivated children of a ribbon when navigating in a ribbon.
=> Navigation improvements

.travis.yml, Brewfile, CMakeLists.txt, lib/irrlicht/include/IrrCompileConfig.h
Replaces https://github.com/supertuxkart/stk-code/pull/3336
=> Add macOS to travis builds, fix server-only builds on macOS, msc. fixes

src/replay/replay_play.hpp, src/states_screens/ghost_replay_selection.cpp, src/states_screens/ghost_replay_selection.hpp
This allows better sorting by preserving relative order when elements are equal according to the main sorting key.
For example, you can sort by time and then by track name, and you'll get replays grouped by track, and for each track they will be sorted by time.
This is also useful when using the compare ghost feature : if you sort by time, select a ghost, use the compare ghost option, then all the possibilities will be sorted by time.
The code change is trivial, as it's simply replacing std::sort by std::stable_sort
=> Use a stable sort for replay list sorting

src/guiengine/widgets/list_widget.cpp, src/guiengine/widgets/list_widget.hpp, src/states_screens/addons_screen.cpp, src/states_screens/addons_screen.hpp, src/states_screens/ghost_replay_selection.cpp, src/states_screens/ghost_replay_selection.hpp, src/states_screens/online_profile_friends.cpp, src/states_screens/online_profile_friends.hpp, src/states_screens/server_selection.cpp, src/states_screens/server_selection.hpp
Some sortable lists (ghost replay list, server selection) inverted sorting order on each click on a column, even if it was another one. This behavior didn't match the UI sorting indication (up/down triangle) and was weird and confusing.
Some others had custom code managing this.
With this PR, the main logic to decide to use default/ascending/descending sorting is done in the list widget, reusing the values computed for the UI indicator ; and all lists have been adapted accordingly.
The friends comparison is also made less redundant and a default sort to show the closest server by distance for the server selection screen has been added.
Fix #3366
=> Fix list sorting

src/guiengine/widgets/spinner_widget.cpp
This fixes the sound issue reported by not triggering the callback when moving to the other arrow of the spinner with keyboard navigation.
As the eventCallback for spinner was previously only used when the state of the spinner was changed, this should not break anything ; the callback is still triggered when changing the spinner state with the select/fire keys.
=> Fix sound issue with spinner in audio options

src/karts/kart_properties.cpp, src/karts/kart_properties_manager.cpp, src/karts/kart_properties_manager.hpp
This uses the list of kart types in the XML file, without hardcoding valid types in code ; so it still works if someone change the names and/or numbers of kart types.
Consequently, the default type is "light" because it is the first in the list.
Fixes #3375
=> Assign kart type to karts not having a valid one

src/race/race_manager.hpp, src/states_screens/race_result_gui.cpp, src/states_screens/track_info_screen.cpp
The ghost replay screen already, and since a long time, display times with the precision to the ms.
It only makes sense to use the same precision for the modes available in ghost replay ; especially for time-trials, and considering that the bigger issues with the finish time accuracy have been fixed (though one known issue remains).
=> Display time-trial and egg hunt times up to the ms

data/gui/ghost_replay_selection.stkgui, src/guiengine/widgets/CGUISTKListBox.cpp, src/states_screens/dialogs/ghost_replay_info_dialog.cpp, src/states_screens/ghost_replay_selection.cpp, src/states_screens/ghost_replay_selection.hpp
The icons are based on the kart model listed in the replay files. If the model is unknown, a "?" icon is displayed.
This PR also adds the ghost icon to the replay info dialog (when selecting a specific replay in the list).
To avoid the replay list being crammed, the number of players column is now hidden by default (only displayed if a checkbox is unchecked), considering that >99% of replays are single player.
Known issue : the replay info dialog list overflows slightly to the right of the dialog.
Fix #3365
=> Add kart icons to the ghost replay list

src/guiengine/widgets/list_widget.cpp
The buttons for the headers use the width of the list minus the scrollbar, and a dummy disabled button allows to not have an empty top-right corner.
=> Align column header with cells in lists

src/modes/easter_egg_hunt.cpp, src/modes/easter_egg_hunt.hpp
getTime() is called immediately when the end condition (all egs collected) is detected, and the result is saved (and not changed afterwards : isRaceOver is called every frame even after it has return true) ; instead of calling it only later when the time is going to be displayed.
The time displayed at the end of the race now matches the ghost's finish time.
=> Fix egg hunt finish time

src/states_screens/options_screen_video.cpp
As discussed on IRC, useful for windowed mode on low-res laptops, or for 720p recording.
=> Add 1280x720 as an available resolution if irrlicht doesn't report it

src/karts/controller/skidding_ai.cpp
Changes : 
- At all AI skill levels, disable item collection and avoidance (trying to get good items, avoid bananas and bubble gums, etc)
- Change the max speed at which the AI will go depending on AI item skill (it will stop accelerating until it's under that speed)
- Change the steering restriction according to AI item skill
=> Multiple AI levels when view is hidden by a plunger

src/modes/soccer_world.hpp, src/modes/tutorial_world.hpp, src/modes/world.hpp, src/modes/world_status.hpp, src/states_screens/race_gui.cpp
The timer doesn't stop after a goal, having it not displayed gives the wrong impression it is.
I also rewrote some related code, as there was a duplication of checks between shouldDrawTimer and custom checks in race_gui.cpp
=> Display soccer timer after a goal

src/karts/max_speed.cpp, src/karts/max_speed.hpp, src/karts/skidding.cpp
Fixes #3387
This implements the desired behavior described in the issue : 
> the red bonus lasts to its normal end, but if the yellow bonus is supposed to finish later, the kart transitions from the red bonus to the yellow bonus rather than having none
If the yellow skid bonus is obtained during the red skid fade-out phase, the two bonus can overlap for a split second, but it's both very minor in effect and hard to trigger, so negligible.
=> Don't remove red skid bonus when getting a yellow skid bonus

src/modes/world.cpp, src/race/highscores.cpp, src/race/race_manager.cpp, src/race/race_manager.hpp
Races against a ghost replay were erroneously considered by highscore code as 2-karts races ; this PR makes the ghost kart not count.
Fix #3413
=> Don't count ghost karts for highscores

data/kart_characteristics.xml, src/karts/kart.cpp, src/karts/kart_properties.cpp, src/karts/skidding.cpp
This PR makes the turn radius of all karts independent of their length. It now only depends on the value defined in kart_characteristics.xml.
I have deliberately not included a rework of the values in kart_characteristics.xml ; but for information, they are close to the tighter turn radius observed before.
The turn radius at 25 of speed is now ~15 ; while the previous values for a few karts were : 
- Wilber : ~14,88
- Tux : ~16,15
- Emule : ~18,65
- Adiumy : ~22,4
=> Fix the turn radius bug

src/modes/linear_world.cpp, src/tracks/track_sector.cpp, src/tracks/track_sector.hpp
This fixes :
- Kart being incorrectly considered first when crossing the lapline off-road
- Distance freezing when going outside of the drivequads, which can happen with normal driving in many places. This had a slightly bad effect on kart positions, and a very bad effects on the live difference feature.
- Distance freezing in cannons (but it only works well if the kart is considered ~on-road, the interpolation tends to fail badly ; for example it works fine in Cornfield Crossing if I go in the cannon slowly, but if I go fast entering it, it will do a very poor interpolation midway in the cannon). I suspect that a full fix may require alterations of the tracks with cannons where it doesn't work well.
The rescue node is kept at the last drivegraph where the kart was on-road, so e.g. …
=> Don't have the distance frozen when going off-road/in cannons

src/input/input_manager.cpp, src/input/input_manager.hpp
Fixes issue #3304 
Previously, the timer only worked properly on joysticks I believe, which has now been fixed, and scrolling speeds up if you hold the key!
=> Fix close inputs being throttled, and speed up scrolling when a key is held

data/gui/screens/grand_prix_editor.stkgui, src/guiengine/widgets/dynamic_ribbon_widget.cpp, src/guiengine/widgets/dynamic_ribbon_widget.hpp, src/guiengine/widgets/ribbon_widget.cpp
Fixes issue #3474 
The issue would only occur as shown in the issue screenshot when you clicked another prix first, and then clicked one where the names were too long. This is because font scaling is done in buildInternalStructure() which was not being called if the number of items was the same as the previous list. This issue was fixed with the first commit.
Second commit adds word wrap, which was suggested in the issue and looks better than tiny text.
=> GP Editor Word Wrap

src/guiengine/widgets/dynamic_ribbon_widget.cpp
Partially fixes #3474 
This pull request ensures that the font size is always updated when DynamicRibbonWidget items are updated by moving the font sizing code to updateItemDisplay() instead up buildInternalStructure(), which is only called when the number of items is changed. The text overlap occurred because the build-in prixs have the same number of items and switching between them didn't call buildInternalStructure(), so the font size wasn't updated.
This pull request doesn't implement word wrap, it only ensures DynamicRibbonWidget behaves consistently and as expected.
=> Always update font size in DynamicRibbonWidget

src/graphics/camera_normal.cpp
Noticed that bug too late, sorry
=> Fix for gyroscope camera using world coordinates instead of camera orientation

src/states_screens/race_gui.cpp, src/states_screens/race_gui.hpp, src/states_screens/race_gui_base.cpp, src/states_screens/race_gui_base.hpp
This PR adds the lap flag, that is used in the current Race UI as a symbol for the lap, to the kart icons if they have finished the race. I think this is really informative because you may adjust your strategy if you know the karts in front of you are already finished.
I tested this in single player, splitscreen and online play and made sure there are no problems with the other game modes (The lap icons will only be shown for normal races and time trials)
Here is a video: https://youtu.be/Em5OfQT3cBk
=> added lap icon to the the kart icons in RaceUI that have finished the race already

lib/irrlicht/source/Irrlicht/CIrrDeviceLinux.cpp
The decimal key was not registering on the number pad as the decimal
key, it was deleting the numbers of the IP address making it impossible
to use the num pad solely for entering an IP.
Fixes #3602
=> Fix for when attempting to input a server IP address on the num pad

src/states_screens/online/online_profile_achievements.cpp, src/states_screens/online/online_profile_achievements.hpp
Fixes #3513 
Makes the achievements list sortable by implementing IListWidgetHeaderListener.
I used online_profile_friends as a model, the resulting class structure is very similar.
Works with both the local achievements screen and viewing another online player's achievements.
=> Achievement sorting

src/karts/controller/player_controller.cpp, src/karts/kart.cpp
It was possible to fire items before the race started. This is an issue for Time Trial races, where you could waste your boosters during startup.
This pull request fixes this problem. Also, pushing the fire button no longer induces the Penalty Time, there is no reason to penalize here.
=> Fix fire before start

src/items/powerup_manager.cpp
There are complaints of people getting too much often caked by AIs very early in a race. As everyone is packed during the first ~10 s, explosive homing items tend to create a lot of mess and frustration in this situation.
In this pull request, I propose a simple patch that disables the rubber ball and the cake during the first 15 s by replacing them by bowling balls.
As this is my first pull request here, I hope that I did this right.
=> Prevent early explosive items

lib/irrlicht/source/Irrlicht/CIrrDeviceWayland.cpp
This code calls *close*, which requires *unistd.h* which is currently only in the #if block. Fix build when _IRR_COMPILE_WITH_JOYSTICK_EVENTS_ is not set by moving the #include.
=> Fix build without _IRR_COMPILE_WITH_JOYSTICK_EVENTS_

lib/irrlicht/source/Irrlicht/CIrrDeviceWayland.cpp
FreeBSD doesn't have linux/joystick.h. Fix build on FreeBSD when joystick support is enabled (the default).
=> Fix build with joystick on FreeBSD

data/stk_config.xml, src/config/stk_config.cpp, src/config/stk_config.hpp, src/tracks/track.cpp
Some addon tracks have set a music in their track.xml that can't be found (either because it was removed from the game in the meantime or the author forgot to include that file). When playing these tracks no music is played at all, which just doesn't feel right.
With this pull request a default music will be played in such cases. The default music can be specified in the stk_config.xml where also the title music is specified.
I chose "kart_grand_prix.music" as default because it (at least for me) always felt like the standard song and I think it just fits almost every possible track well. But that can be easily changed.
=> Using a default music if specified music of track was not found

src/graphics/camera.cpp, src/graphics/camera_normal.cpp, src/graphics/show_curve.cpp, src/graphics/slip_stream.cpp, src/guiengine/skin.cpp, src/input/input_manager.cpp, src/input/wiimote.cpp, src/karts/controller/ai_base_controller.cpp, src/karts/controller/soccer_ai.cpp, src/karts/kart.cpp, src/karts/skidding.cpp, src/states_screens/feature_unlocked.cpp, src/states_screens/race_gui_base.cpp, src/states_screens/race_result_gui.cpp, src/tracks/terrain_info.cpp
Replace calls to double-precision trigonometric functions to their floating-point counterparts. Depending on this platform and standard math library, this can result in less computation.
=> Use floating trigonometric functions

src/guiengine/widget.cpp
with my PR for widget collapsing functions #3664, the widgets for soccer target type (goals or time), introduced in PR #3638, the widgets are not shown if the soccer track info screen is shown before a track info screen for another game mode. Sorry for that, this PR fixes the wrong behavior of the function setCollapsed.
=> fix for widget collapsing

src/utils/separate_process.cpp
This makes it possible to create a local multiplayer server on FreeBSD with the in-game menu.
=> Implement getCurrentExecutableLocation() on FreeBSD

src/config/user_config.hpp, src/main.cpp, src/states_screens/dialogs/message_dialog.cpp, src/states_screens/dialogs/message_dialog.hpp, src/states_screens/options/options_screen_general.cpp
First fix for #3378: sending hardware stats is now opt-in (no default to send hardware stats anymore). Fixes also incorrect help message and incorrect status display if hw-stats are reported or not, and made the chat option (in)visible same as hw-stats.
Note that the order of entries in the 'internet' option is strange (the 'always show login' option is not strictly an internet-only option, since it also affects local-only accounts), but I am not sure why this order was chosen, so I left this unchanged.
Combining internet-access and hw-stats with just one option is bad now that stk is gdpr compliant, since it must now default to internet-off :( But I can't see an easy and convenient location - best option imho: remove the HW statistic, since we are actually not using the stats anymore.
=> Gdpr compliance

src/network/server.cpp
... to make it more obvious what the STK team does not operate those servers.
This is a fix for #3691 good enough for the next release, when a proper solution can be implemented. 
Note that some strings modified in this pull request are temporary only (i.e. to make sure we keep already translated strings that we will need later). 
@Benau, can you check that I didn't break anything (especially I found it hard to understand that m_server_owner_lower_case_name was "Official" (capitalised), I used all lower case now, please check that I didn't break anything ;) ).
=> For now rename 'official' servers to 'trusted'

CMakeLists.txt, cmake/FindWiiUse.cmake
Adapted from Fedora patch by @ignatenkobrain:
https://src.fedoraproject.org/rpms/supertuxkart/blob/be85787d3485c477d23419b19c382b2186020016/f/0002-Unbundle-WiiUse.patch
Tested successfully on Mageia 7 with `-DUSE_SYSTEM_WIIUSE=ON`, currently building with `=OFF` to confirm that the original system still works as expected.
=> CMake: Add option to use system WiiUse

src/addons/news_manager.cpp, src/addons/news_manager.hpp
I know this is not encouraged, but can this be cherry picked into the `0.10` branch? as it just changes the news filename to be downloaded.
=> Fix #3842 by always using https links

CMakeLists.txt
The system version was preferred before but it wasn't possible to explicitly disable it, making its use 
automagic, which is bad for packaging.
=> CMake: Add option to use system Squish library

src/states_screens/addons_screen.cpp, src/states_screens/online/server_selection.cpp, src/states_screens/options/options_screen_input.cpp
To make benau happy, those rows should be smaller.
Maybe i'm used to the big icons in 4k.
P.S.Commit N0.2's description is wrong.
=> IV for better row size

lib/irrlicht/source/Irrlicht/CIrrDeviceWayland.cpp
> This change ensures that SuperTuxKart will not keep running in the background when the compositor crashes and doesn't close the STK main window.
Errors with Wayland are always fatal and prohibit further actions with Wayland connection, so if the return value for  `wl_display_dispatch_pending` is ever `-1`, then the connection will have closed.  See also the documentation for [`wl_display_dispatch_pending`](https://wayland.freedesktop.org/docs/html/apb.html#Client-classwl__display_1ac4b6b5ad31932bc3830ff362d2938560). 
This change can be tested by running a Wayland compositor (say, `weston`, nested under something; then inside a child terminal, orphaning the STK process with `supertuxkart & disown` so that it isn't automatically cleaned up when Weston exists, and then running `killall …
=> Close program when Wayland connection hangs up

data/po/pull_from_transifex.sh
Currently (TX client 0.13.5 and obviously latest server) pull_from_transifex.sh initialization is broken. It wants me to manually set up file mappings. I do not remember having to do that in the past. Apparently `tx init` is running interactive `tx config`, but it can be disabled with `--skipsetup`. We do automatic configuration afterwards with `tx set --auto-remote`. Moreover, `tx set` is now deprecated in favor of `tx config`.
Also Transifex now complains it wants HTTPS and the domain changed from `.net` to `.com`.
=> Fix pull_from_transifex.sh due to Transifex changes

src/replay/replay_play.cpp
[Cppcheck 1.88](https://github.com/danmar/cppcheck) gives the following warnings about the `sscanf()` calls in the method `ReplayPlay::addReplayFile()`. I changed the sscanf calls from `%s` to `%1023s` because `s1` is a 1024 byte buffer and Cppcheck recommends to make the field width limit for `%s` one less than the buffer size to leave space for the null byte which ends a string. Without the field width limits in the format strings, STK probably won't crash unless the replay files are corrupted somehow (e.g. with `zzuf` or `afl` fuzzers).
Cppcheck warnings:
```
[replay\replay_play.cpp:145]: (warning) sscanf() without field width limits can crash with huge input data.
[replay\replay_play.cpp:165]: (warning) sscanf() without field width limits can crash with huge input data. …
```
=> Limit sscanf %s fields to prevent possible crash.

src/states_screens/dialogs/achievement_progress_dialog.cpp
The singular form of `battle` here is inconsistent with the other achievement goal strings. Just look at the surrounding code.
This resolves two Transifex issues.
=> Make achievement goal string consistent

CMakeLists.txt
On some architectures it is required to explicitely link against
libatomic to use e.g. 8 byte atomics.
Check during configuration if it compiles without libatomic. If not,
add it to target_link_libraries.
Noticed on Debian build servers: https://bugs.debian.org/934799
```
```
=> Link against libatomic if required

data/gui/screens/track_info.stkgui, src/config/user_config.hpp, src/modes/world.cpp, src/states_screens/track_info_screen.cpp, src/states_screens/track_info_screen.hpp
Hi, 
This is an improved version compared to the previous PR (#4061). Now we can set the number of Red/Blue AI separately. It also works for split-screen. Having 8 split-screen will disable the spinners related to the AI. If increasing the number of red AI to num_red_ai+num_blue_ai>max_ai, the blue AI number will decrease by 1 automatically. The upper bound of each spinner is also taken care of.
I still added the spinner with two options: Balanced and Custom. This simplifies the implementation.
The spinner does not scale properly on low resolutions. I believe it can be solved with maosen's code.
The code may need to be cleaned a bit.
```
GNU General Public License version 3 or any later version …
```
=> Add options to control the number of red/blue AI in soccer mode

src/states_screens/dialogs/press_a_key_dialog.cpp, src/states_screens/dialogs/press_a_key_dialog.hpp, src/states_screens/options/options_screen_device.cpp
* Added a check for the keyboard input device and changed the text of the "title" widget using **Widget->setText("id")** method
* Have hard coded the string **"Press any key..."** in **src/states_screens/dialogs/press_a_key_dialog.cpp** 
****
```
```
=> Fix for #3444

src/states_screens/race_gui_base.cpp
In addressing issue #4089, I make the font smaller based on the icon size, see below:
```
```
=> Rescale the time font if icon is small (solve issue #4089)

src/states_screens/race_gui_base.cpp
Feature that shows the items of every player in the icons at left, similar to some Mario Karts.
Personally, I really liked that feature, and maybe others Stk players might too. It would also make races a bit more exciting and strategic by having a way to anticipate the others' actions. And I can finally see who is sending me all these Basket Balls Lol.
More importantly, this is currently a way to cheat by having this feature while others don't, and I don't see any real cons to see what items others have (other than "items should be secret", but again, as we can cheat easily...).
Sorry, I can't test this online for now so hopefully that works for it too, but I don't see why it should not work.
Should work in all modes, though there is no icons at left in Soccer, but I think that this …
=> Show everyone's items with the left characters icons

data/gui/screens/options_ui.stkgui, sources.cmake, src/challenges/story_mode_status.cpp, src/challenges/story_mode_status.hpp, src/challenges/story_mode_timer.cpp, src/challenges/story_mode_timer.hpp, src/config/player_manager.cpp, src/config/player_profile.cpp, src/config/player_profile.hpp, src/config/user_config.hpp, src/graphics/irr_driver.cpp, src/graphics/irr_driver.hpp, src/guiengine/engine.cpp, src/guiengine/engine.hpp, src/main.cpp, src/states_screens/dialogs/race_paused_dialog.cpp, src/states_screens/dialogs/race_paused_dialog.hpp, src/states_screens/main_menu_screen.cpp, src/states_screens/options/options_screen_ui.cpp, src/states_screens/race_gui.cpp, src/states_screens/race_gui_overworld.cpp, src/states_screens/race_result_gui.cpp
This is the result of my previous work, with a port of the timer version that was developed for a 1.0 mod. It has been used by several players so no major issue should exist, though UI and other elements may require adjustment to smooth some rough edges.
It features both a casual story mode timer storing the total time to complete the story mode (on by default) and a "speedrun" timer (off by default). The casual timer is paused whenever the player exits story mode, and supports play over multiple sessions. It is only displayed in the overworld and during challenges ; while the speedrun timer is permanently displayed.
Fix #2907
=> Compute and display a story mode timer

src/utils/string_utils.cpp
This is a small change to fix a Cppcheck warning.
```[utils\string_utils.cpp:806]: (warning) %x in format string (no. 1) requires 'unsigned int *' but the argument type is 'signed int *'.  ```
```
```
=> Use unsigned int with %x format string

src/input/input_manager.cpp, src/input/keyboard_static_keys.hpp, src/utils/debug.cpp, src/utils/debug.hpp
```
```
Hello, as indicated in input_manager.cpp , debug actions had to be moved in debug.cpp.
Here my proposal of refactoring:
- key with no associated action are parsed by Debug::handleStaticAction
- given they are already computed : the key, its value and modifiers, and current world are forwarded to the Debug method 
- in order to make the static shortcut more understandable, they are all in the same file (new file …
=> refactor debug keyboard input

src/network/protocols/server_lobby.cpp, src/network/stk_peer.cpp, src/network/stk_peer.hpp
```
```
In chat, ensure that for a person writing more than 3 consecutive messages (less than 5s between 2 messages) prevents display an other message from him while the next 5 seconds.
=> add message freguency limit in chat #3893

src/main.cpp
Came across these when working in my branch.
```
```
=> Fix CMD flags in main.cpp

src/scriptengine/script_track.cpp
This change attempts to expose the KartType (local player, networked player, AI, etc.) to scripting.
This is useful if a track creator wants an action to only occur if triggered by a real player, or only if triggered by a non-networked player (e.g. alternate route music in Frozen Drive unofficial add-on).
I have rushed this in to try and get it added in STK 1.1 and I have not yet been able to configure and build STK from source, **so this change is currently untested!** If there is still time before 1.1, I can try building myself but otherwise I may not be able to.
I have placed this function in the Track section because it uses the race manager. Please let me know if the Kart section is more appropriate.
```
By creating a pull request in stk-code, you hereby agree to dual-license your …
```
=> Expose getKartType(int kartId) to scripting

src/network/protocols/client_lobby.cpp, src/network/protocols/server_lobby.cpp
Now we can:
**/liststkaddon** : list all addons
**/liststkaddon** **-kart** : list all kart addons
**/liststkaddon** island: find addons that match 'island' 
**/liststkaddon** **-track** island : find all tracks that match 'island'
available options: -kart, -track, -arena
Similarly, we can use
**/listlocaladdon** : -kart, -track/-arena, -skin. Note: no distinguish between -track and -arena.
**/listserveraddon** : -track, -arena, -kart, -soccer.
compare() -> find(): a better search.
```
Keep the above …
```
=> make /liststkaddon, /listlocaladdon, /listserveraddon more friendly

.travis.yml, lib/irrlicht/source/Irrlicht/COSOperator.cpp, src/network/protocols/lobby_protocol.hpp
```
```
I'm not sure if SuperTuxKart is supported on non-Linux and macOS *nix platforms like BSD, as this might break it.
Anyways, this fixes #4172.
=> Include linux/sysctl.h rather than sys/sysctl.h on non-glibc systems

src/utils/log.hpp
```
```
The `__GNUC__` check didn't actually work on Musl and it still got activated, even though it should've went for the else condition instead. Changing it to `__GLIBC__` worked and is the recommended way of doing it.
Then defining `VALIST` as `va_list` rather than `char*` made it compile successfully.
This fixes #4173.
=> Define VALIST as va_list rather than char* on non-glibc systems

INSTALL.md, lib/irrlicht/source/Irrlicht/MacOSX/CIrrDeviceMacOSX.h
Silencing deprecated OpenDL api warnings in recent MacOS releases.
Needed to set openssl for curl.
```
```
=> Mac OS little update propsal.

src/scriptengine/script_gui.cpp
As @Benau suggested to use MessageQueue for *making the Game Flow of the Tutorial smoother* (#4187), this Pull Request enable MessageQueue for Track-Scripts.
For me it works well with MessageQueue, however i think we could make the Font of a Message a little bit bigger, since it is quite small, especially on mobile.
```
```
=> Enabling MessageQueue for Scripting

src/utils/string_utils.cpp, src/utils/string_utils.hpp
The function is rather bad because it doesn't exit the loop early and doesn't check for whitespace that is not exactly " ", such as \t, \n. Since the function is unused, it can simply be removed instead of improving it.
```
```
=> Remove StringUtils::notEmpty

src/race/race_manager.hpp, src/states_screens/dialogs/ghost_replay_info_dialog.cpp, src/states_screens/ghost_replay_selection.cpp, src/states_screens/race_gui.cpp, src/utils/string_utils.hpp
There is no reason to have centiseconds here and milliseconds there...
The only drawback is that most of the time, the time in the finish screen is different of a few ms from the one shown at the left icon due to the fact that one is based on an interpolation and the other on the Tick number (or sometimes due to a bug, https://www.youtube.com/watch?v=MMbPQWepM8k ).
But that is an issue that should be fixed, and we should eventually have consistent times and precision everywhere anyway...
The Pull Request also changes the time string in the Ghosts List/Dialog to have something like "1:12:346" rather than "72.3456s", or "1:23.000" rather than "83s".
There should be a fixed width font for times...
Well if I could I would release my Pull Requests to the Public Domain... …
=> Always show times in ms

lib/irrlicht/source/Irrlicht/COpenGLExtensionHandler.h, lib/irrlicht/source/Irrlicht/COpenGLSLMaterialRenderer.h, lib/irrlicht/source/Irrlicht/COpenGLShaderMaterialRenderer.h, lib/irrlicht/source/Irrlicht/COpenGLTexture.h, src/audio/music_manager.cpp, src/audio/music_ogg.cpp, src/audio/music_ogg.hpp, src/audio/sfx_buffer.cpp, src/audio/sfx_buffer.hpp, src/audio/sfx_manager.cpp, src/audio/sfx_manager.hpp, src/audio/sfx_openal.cpp, src/audio/sfx_openal.hpp, src/graphics/gl_headers.hpp, src/utils/crash_reporting.cpp
OpenGL deprecated APIs, gl/gl3 inclusion, OpenAL deprecated API.
Implementing process path for the crash reporter.
```
```
=> Reducing significantly build warning on MacOS

lib/irrlicht/source/Irrlicht/CGUIListBox.cpp, src/config/hardware_stats.cpp, src/guiengine/widgets/CGUISTKListBox.cpp
to avoid confusions even though they have same values.
FreeBSD recognised as os in stats point of view.
```
```
=> removing compilation warning explicitly showing enum origin

CMakeLists.txt
dns resolution belongs to the libc on those systems.
little server connection checking update proposal.
```
```
=> Build fix on *BSD.

.gitignore
Hi, since it is in the official document, I suggest adding xcode_build to the ignore file.
```
```
=> add xcode_build to .gitignore

data/gui/screens/options_device.stkgui, src/input/device_config.cpp, src/input/device_config.hpp, src/states_screens/options/options_screen_device.cpp, src/states_screens/options/options_screen_input.cpp
Issue #3408
Add a button for rename a configuration.
```
```
=> Add rename config option

src/states_screens/track_info_screen.cpp
It is not necessary to restrict player number > 0. If there is at least one AI in the team, 0 player should be allowed. We only need to deal with the case of 0 player and 0 AI.
```
```
=> allow 0 player number if there is AI

src/graphics/camera.cpp, src/graphics/camera.hpp, src/graphics/camera_normal.cpp, src/network/protocols/client_lobby.cpp
This PR, add a camera mode to spectate soccer in large isometric view  that follow the ball (switchable with accel/brake keys).
Related to issue: https://github.com/supertuxkart/stk-code/issues/4238 (no need to check the issue, it is just a technical question with some thougths about UI — a mirror like in _crazyracing kartrider_ —).
```
```
=> add a camera mode to spectate soccer in large view that follows the ball

data/kart_characteristics.xml, src/graphics/camera_normal.cpp, src/graphics/camera_normal.hpp, src/karts/abstract_characteristic.cpp, src/karts/abstract_characteristic.hpp, src/karts/kart_properties.cpp, src/karts/kart_properties.hpp, src/karts/xml_characteristic.cpp
This PR restore the usage of _forward-up-angle_ which was unused in code because of hardcoded smoothing. It is an attempt to reconcile the hard coded dynamic camera with xml settings. Default settings change nothing to the camera.
Additionnally, smoothing when camera is pointing forward can be disabled with new parameter _forward-smoothing_.
Related to : https://github.com/supertuxkart/stk-code/issues/4154
Impact `data/kart_characteristics.xml`.
```xml 
<camera distance="1.0"
forward-up-angle="0" forward-smoothing="true"
backward-up-angle="5" />
```
```
This includes your previous …
```
=> camera parameter forward-smoothing  and restore use of forward-up-angle 

src/config/user_config.hpp, src/graphics/camera.cpp, src/graphics/camera.hpp, src/graphics/camera_normal.cpp, src/network/protocols/client_lobby.cpp, src/states_screens/race_gui.cpp
Hello,  
following the addition of parameters camera distance and angle in `kart_characteristics.xml` , i observed that soccer camera for spectator mode was too much far. Too, in context of recording video, kim notified a view was missing.
Therefore, the changes are the following :
- add in `user_config.xml`, settings for spectator camera angle and distance 
- add a new camera mode for to have a top view that look the ball in soccer mode,  and look the kart else
- in order to have a full view of the situation, remove the appearance of the player item and speed information when choosing a spectator camera mode
```
Mozilla Public License …
```
=> add top view for spectating & rm gui item view for this camera mode

src/config/user_config.hpp, src/graphics/camera_normal.cpp
In user config, add a bool option `reverse-look-use-soccer-cam` to use almost the same camera than spectator camera soccer except angle and distance are the ones of reverse camera mode.
To use it : set the option to "true"; start a soccer game; use rear view mirror that is no more rear view mirror in this mode, but a camera that follows the ball.
On apply to soccer mode, not completely useful (given the minimap make the job), but :
- completely stylish :laughing: 
- familiar to Rocket League users
``` …
```
=> add option to substitute look back camera by soccer ball camera

data/gui/screens/options_ui.stkgui, src/states_screens/options/options_screen_ui.cpp
Hello !
I propose to replace the checkbox that activate horizontal splits in multiplayer mode by a spinner.
The aim is to clarify this part of the interface, because (IMO) :
-  the user need to knows explicitly which current split in multiplayer mode.
-  activating horizontal split is a global rendering option, not an additionnal widget like "display FPS". Therefore this option shall be placed in same group that theming.
```
```
=> replace split screen horizontal checkbox by a spinner 

src/input/gamepad_config.cpp
Although there's not much we can do about accel on the shoulder-less config, we can at least make the menu keys and pause/rescue consistent with the shouldered config.
```
```
=> Update shoulder-less controller mapping

src/states_screens/race_gui_base.cpp
Different languages use different quotation marks and spacing
(e.g., « Song title » in French), so the formatting needs
to be translatable.
```
```
=> Make formatting of song title translatable

src/scriptengine/script_track.cpp
```
```
**Note: due to an issue with my setup, I haven't been able to compile and test this patch.** However it is very basic and I am willing to test a compiled version (either Win or Lin).
This feature was requested by three users in [this forum thread](https://forum.freegamedev.net/viewtopic.php?f=18&t=13078#p91399). Potential uses include:
* assisting AI and slow drivers over gaps or jumps on low difficulty settings
* tailoring jump …
=> Expose getDifficulty() to scripting

CMakeLists.txt, lib/angelscript/source/as_config.h, lib/irrlicht/include/IrrCompileConfig.h, lib/irrlicht/source/Irrlicht/CFileSystem.cpp, lib/irrlicht/source/Irrlicht/COSOperator.cpp, src/network/socket_address.hpp, src/utils/string_utils.cpp
```
```
So, this took a while. This pull request is meant to add support for the POSIX-compatible Haiku operating system and exists largely because of @Benau and @PulkoMandy.
Multiplayer works, after a few small modifications to the socket code. The game runs under SDL (which is supported under Haiku) and OpenGL.
I only managed to try it in a KVM virtual machine (aka. it runs under the llvmpipeline) and not bare metal/physical hardware. …
=> Add support for Haiku operating system

data/skins/coal/stkskin.xml, data/skins/forest/stkskin.xml, data/skins/modern/stkskin.xml, data/skins/ocean/stkskin.xml, data/skins/peach/stkskin.xml, data/skins/ruby/stkskin.xml, src/guiengine/widgets/list_widget.cpp
Hi, I made the red team color in the player list also configurable in the skin. This can provide more flexibility for skin design.
```
```
=> Make red team color also configurable

src/states_screens/kart_selection.cpp
On the kart selection screen, the kart name is shown using the default black color. This does not work well with a dark skin. Here I use the color provided in skin for it.
```
```
=> Use skin color for the kart name label on kart selection screen

src/io/file_manager.cpp
I'm playing with running various games on a mobile GNU/Linux device. It's often the case that when a game has existing mobile support (Android and/or iOS), it then relies on some preprocessor directives in order to adjust some of its UI, available options etc. to mobile devices - so when I've noticed `MOBILE_STK` across the SuperTuxKart's code, I decided to try compiling it with it to see whether it will bring some benefits. It compiled fine.
However, running it had some unforeseen consequences.
In `src/io/file_manager.cpp`:
```c
#ifdef MOBILE_STK
m_stk_assets_download_dir = getenv("HOME");
#ifdef IOS_STK
m_stk_assets_download_dir += "/Library/Application Support/SuperTuxKart/stk-assets/";
#elif defined (ANDROID)
m_stk_assets_download_dir += "/stk-assets/";
#endif
#else
```
As I was …
=> file_manager: Emit a compiler error when no asset dir is defined for mobile platform

data/gui/screens/grand_prix_lose.stkgui, data/gui/screens/grand_prix_win.stkgui
On HiDPI screens these buttons were too small.
```
```
=> Fix button spacing in grand_prix_lose.stkgui and grand_prix_win.stkgui

src/states_screens/track_info_screen.cpp
Reuse the AI number for cases like: 1 red player + 0 red AI + 7 blue AI
```
```
=> fix a small bug in reusing previously saved AI number

src/network/network_config.cpp
```
```
This allows the game to build for distros using musl libc, such as Void and Alpine, since musl does not implement `ns_name_ntop`. Does this patch keep the intended behavior for that code? I am opening this PR since it isn't clear whether this function will be added to musl, and it would be best if such changes were discussed with upstream.
=> network_config: use ns_name_uncompress

CMakeLists.txt
...to avoid picking includes from system angelscript when bundled one is used
Fixes #4372
```
```
=> Fix include path order

src/graphics/weather.cpp
```
```
Fixes #4354 
It used to be that thunder sounds would still play after pausing the game since the sounds were a part of Weather::update which gets called every frame by World::updateGraphics. This was solved with a check in Weather::update to examine wether the game is paused or not, however I guess another solution would be to separate the updating of weather graphics and sound since World::updateGraphics probably shouldn't …
=> Fixes thunder sounds playing during paused game

data/gui/screens/options_video.stkgui
With the font size set to "Very Large" and the theme set to "Cartoon", the Apply button went slightly outside of the main box.  This fixes that by putting the two checkboxes on the same row, which saves a bit of valuable horizontal space.
```
```
=> Condense checkboxes in video options

src/guiengine/screen.cpp, src/guiengine/screen.hpp, src/main_loop.cpp, src/states_screens/credits.cpp, src/states_screens/state_manager.cpp, src/states_screens/state_manager.hpp
We should let VSync/m_max_fps (which defaults to 120) do their job.  If a monitor has a refresh rate even slightly higher than 60FPS (e.g. 60.0007FPS), throttling will introduce stutters, even more so at modern high refresh rates (75, 90, 120, etc.)
This also cleans up the code, e.g. the var name `m_throttle_fps` was also being used in `main_loop.[c/h]pp` for a different function, despite having the same var name.
```
```
=> Remove separate menu FPS throttling

src/guiengine/skin.cpp, src/karts/kart_properties.cpp
Hi, I made it possible to load official karts' icons from the skin folder (svg icon is also supported). If an icon is not found in the skin folder, then the default one will be loaded.
The folder structure is like:
data/skins/xxx/data/karts/adiumy/xxx.png
Here is what jymis's icons look in game:
Hope you like it.
```
```
=> Skinable kart icons

CMakeLists.txt
```
```
Currently, if SDL2 is built with DirectFB support, build will fail as SDL2 cannot find some DirectFB headers. This patch intends to fix that while still allowing SuperTuxKart to be built without DirectFB if your build of SDL2 does not support it.
As is right now in Alpine Linux we have a downstream patch for this, but it'd be nice to be able to get rid of that with the next release of SuperTuxKart: …
=> Fix build when SDL2 is built with DirectFB support

src/utils/translation.cpp
This pull request fixes a potential access out of bounds found with Cppcheck when reading thaidict.txt. If `u32line` is empty, the program tries to access the zeroth element of `u32line` which is out of bounds when the string is empty.
The fix is simple: just move the `.empty()` check before accessing `u32line[0]`.
Currently thaidict.txt doesn't have any empty lines so no out of bounds access will actually occur.
Cppcheck warnings for translation.cpp:
```
[translation.cpp:271]: (performance) Searching before insertion is not necessary.
[translation.cpp:266] -> [translation.cpp:265]: (warning) Either the condition 'u32line.empty()' is redundant or expression 'u32line[0]' cause access out of bounds.
[translation.cpp:109]: (style) Consider using std::copy algorithm instead of a raw loop. …
```
=> Fix access out of bounds warning with Cppcheck 2.2

data/stk_config.xml, src/audio/music_information.cpp, src/audio/music_information.hpp, src/audio/music_ogg.cpp, src/audio/music_ogg.hpp, src/config/stk_config.cpp, src/config/stk_config.hpp, src/karts/kart.cpp, src/main.cpp, src/states_screens/feature_unlocked.cpp, src/states_screens/grand_prix_lose.cpp, src/states_screens/grand_prix_win.cpp, src/states_screens/race_result_gui.cpp
Adding the following features surrounding music:
- Add support for loop end of music.
- Make composer field in music information files optional. 
- Support playing different music on race results screen (configurable via stk_config.xml).
- Allow configuring grand prix win/lose and feature unlocked music (configurable via stk_config.xml).
Three different soundtracks can play at the end of a race, depending on these three conditions:
- At least one player kart is in 1st place: race_win_theme.music
- All player karts finished in winning positions, but none in 1st place: race_summary.music
- No player karts finished in winning positions: lose_theme.music
- For races with only AI karts and no human players: race_summary.music
The race win music (race_win_theme.music) is from the STK media repo …
=> More configurable music (loop end support, different race result music)

data/gui/dialogs/custom_camera_settings.stkgui, data/gui/screens/options_ui.stkgui, src/config/user_config.hpp, src/states_screens/dialogs/custom_camera_settings.cpp, src/states_screens/options/options_screen_ui.cpp
Hi, I made a few changes on the camera setting:
1. Put the 'ball camera in soccer' back to the custom_camera_settings UI.
2. Add the ability to customize 'camera smoothing' and 'ball camera in soccer' of Standard and Drone chase camera. Gray out the rest settings in the custom_camera_settings UI. The 'Custom...' button will be used for all three cameras.
3. Put the settings of Standard and Drone chase camera in the config file, instead of hard-coded.
Benefit of this PR:
1. The ball camera setting really belongs to the camera setting UI. We can save one line on the option UI.
2. Camera smoothing can also be customizable for Standard and Drone chase camera.
3. For advanced users, they can modify the config file to have better 'Standard' and 'Drone chase' settings for their need. I think it …
=> camera settings

data/gui/dialogs/custom_camera_settings.stkgui, src/guiengine/widgets/spinner_widget.cpp, src/states_screens/dialogs/custom_camera_settings.cpp, src/states_screens/options/options_screen_audio.cpp, src/states_screens/options/options_screen_ui.cpp
Hi, the changes are:
1. When a spinner is not active, still show its value instead of showing "-".
2. Show the camera name in custom_camera_setting UI
3. On the audio setting UI, disable the spinner if the checkbox is not ticked.
Here are some screenshots. Hope you like it.
```
```
=> Few improvements of spinner and option UI

src/states_screens/dialogs/kart_color_slider_dialog.cpp, src/states_screens/race_result_gui.cpp
Hi, some small fix:
1. use default kart color instead of the hardcoded 100
2. deal with the problem of extremely small kart icon on a 4K screen, see following figure:
There are various places where the icon size are based on the original size of the icon. This can be a problem for svg icons. It is better to scale according to the text size.
```
```
=> small fix of kart color slider and kart icon in result screen

src/states_screens/race_gui.cpp, src/states_screens/race_result_gui.cpp
Hi, there are two changes:
1. Make team icon (soccer ball, flag in CTF) scale with text size to better fit high DPI screen and more friendly to svg icons. The soccer ball has a height of 1.5 title font height, and the team flag has a height of 1 title font height. In addition, small fix of the alignment.
2. On the race gui, four spaces can cause problem for monospace fonts, see the following figure. So instead of four spaces, I changed it to 2 zeros.
```
Keep the above statement in the pull request …
```
=> Small fix of icon size on race result ui and space size on race gui

src/graphics/spherical_harmonics.cpp
Spherical harmonics: if no ambient map assigned, use specified color (but correctly)
This is a minor bug I noticed while revamping the Blender exporter tools. Seems like as long no map for the spherical harmonics is used, the ambient color (sun XML node) is interpreted wrongly.
```
```
=> Fixing minor ambient lighting bug

data/gui/screens/options_video.stkgui, lib/irrlicht/include/IrrlichtDevice.h, lib/irrlicht/source/Irrlicht/CIrrDeviceSDL.cpp, lib/irrlicht/source/Irrlicht/CIrrDeviceSDL.h, lib/irrlicht/source/Irrlicht/CIrrDeviceStub.h, src/config/user_config.hpp, src/graphics/shader_based_renderer.cpp, src/states_screens/options/options_screen_video.cpp, src/states_screens/options/options_screen_video.hpp
[UPDATED]
Auto mode adjusts based on your display's DPI in order to hit a target DPI.  Currently it will default to Always Full for render resolution, but High Quality or even Quality might make a good default, community testing is needed.
```
```
=> Add Render resolution (scale_rtts) slider with auto-mode 

.github/workflows/main.yml
```
```
(I also agree to release those changes under CC0 in addition to both of the above licenses)
=> GitHub Actions workflow can now be triggered manually

data/gui/dialogs/custom_camera_settings.stkgui, data/gui/dialogs/custom_video_settings.stkgui, data/gui/dialogs/kart_color_slider.stkgui, src/modes/overworld.cpp, src/states_screens/dialogs/custom_camera_settings.cpp, src/states_screens/dialogs/custom_video_settings.cpp, src/states_screens/dialogs/kart_color_slider_dialog.cpp, src/states_screens/dialogs/kart_color_slider_dialog.hpp, src/states_screens/edit_gp_screen.cpp, src/states_screens/edit_gp_screen.hpp, src/states_screens/main_menu_screen.cpp
The aim of these fixes is to make some of the dialogs and input handling more consistent with what is used elsewhere in the rest of the game.
- Add icon button bars for the kart color slider, custom camera settings, and video settings dialogs
- Open the confirm dialog if exiting the grand prix editor with changes by escape key
- When launching the tutorial or story mode, use the last used device instead of the first keyboard
```
```
=> Several UI fixes

src/main.cpp, src/race/race_manager.cpp
```
```
Seems to lessen loading times somewhat from what I saw :)
We can clock up CPU while loading at the expense of dropping GPU clock to basically nothing.
I would like to see about debugging Irrlicht's filesystem stuff for better performance though, since I think that's where a lot of the bottleneck lies.
=> Clock up CPU while loading on Switch

data/gui/dialogs/debug_slider.stkgui, data/gui/dialogs/tutorial_message_dialog.stkgui, src/config/user_config.hpp, src/graphics/camera_debug.cpp, src/graphics/camera_debug.hpp, src/graphics/irr_driver.cpp, src/input/input_manager.cpp, src/items/powerup.cpp, src/items/powerup.hpp, src/karts/controller/skidding_ai.cpp, src/main.cpp, src/states_screens/dialogs/debug_slider.cpp, src/states_screens/dialogs/debug_slider.hpp, src/states_screens/dialogs/tutorial_message_dialog.cpp, src/utils/debug.cpp, src/utils/debug.hpp
```
```
A significant revamp of the artist debug mode (most changes will not be seen if that mode is disabled) to make it more powerful and add more ways to test things in-game. More significant changes include:
- Kart views changed or added:
- Side of kart view -> Right side of kart view
- Left side of kart view
- Static front of kart view (does not function exactly like looking backwards)
- Camera kart targets added:
- Pick kart from …
=> Improved artist debug mode

src/network/protocols/client_lobby.cpp, src/network/server.hpp
=> Mark servers as password protected on RR_INCORRECT_PASSWORD

CMakeLists.txt
The `/usr/share/pixmaps` location is considered a legacy location for application icons; since the application icons are already installed in the global XDG hicolor theme, then simply stop installing the 512px one in the legacy pixmaps location.
```
```
=> Stop installing app icon in pixmaps location

src/states_screens/addons_screen.cpp, src/states_screens/addons_screen.hpp
This adds the feature requested in the forum: https://forum.freegamedev.net/viewtopic.php?f=17&t=17734
The add-on list is updated whenever the search string is changed.
Since this is my first pull request here, I hope I've not made any mistakes concerning coding style etc.
```
```
=> Automatically update list when search string is changed in addons_screen

src/tracks/drive_graph.cpp
This is related to [a forum post](https://forum.freegamedev.net/viewtopic.php?f=18&t=18044&start=25#p103190) about complex tracks needing a long time to load.
The problem is: When there are multiple alternative drive lines, computeChecklineRequirements() does a lot of unnecessary recursions.
I reworked my approach (different from what I mentioned in the forum post) and this PR produces the correct result while greatly reducing the execution time. As a side effect it also makes sure to not add the same value twice.
```
This includes your previous contribution(s) under the same name …
```
=> speed up computeChecklineRequirements()

CMakeLists.txt, switch/make.sh
Use MojoAL on Switch by default. Removes `USE_SWITCH` and `USE_MOJOAL` from `switch/make.sh`. They are unneeded since NINTENDO_SWITCH. Also refactor USE_SWITCH calculation.
```
```
=> mojoal on switch by default

data/skins/coal/stkskin.xml, data/skins/forest/stkskin.xml, data/skins/ocean/stkskin.xml, data/skins/peach/stkskin.xml, data/skins/ruby/stkskin.xml, src/guiengine/skin.cpp
Use skin color instead of black for tooltip texts.
Also, put gaugefillrainbow in stkskin.xml close to gaugefill (not to confuse skin designer).
```
```
=> Use skin color for tooltips

src/states_screens/race_gui.cpp, src/states_screens/race_gui.hpp, src/states_screens/race_gui_overworld.cpp, src/states_screens/race_gui_overworld.hpp
This makes the speedometer images loadable from the Skin folder. A skin can have its own speedometer.
Not sure if they really need to be defined as _Materials_.
```
```
=> load speedfore.png and speedback.png from skin

data/shaders/IBL.frag
This is a significant improvement in many regards, though I still haven't managed to fix #4574.
Before:
After:
(Ignore the massive FPS difference here, when clicking the launcher icon it defaults to my 3060 but when running from the terminal it defaults to my iGPU.)
```
```
=> Screen-space refection: many fixes + optimization

src/addons/addons_manager.cpp
Currently the notification for new / updated addons (green arrow on addons widget in main menu) disappears after STK is restarted. This PR makes the notification stay as long as there are updates.
There is one corner case which is not addressed here:
When there is an update for an addon, but instead of updating, the user removes that addon, the notification will stay until another addon is installed or STK is restarted.
I think most players won't remove an addon, when there are updates, so it shouldn't be a problem.
If you want me to change it, so that removing an addon also resets the flag, just tell me. This would however not follow your specification from Discord completely... 🤓
```
GNU …
```
=> Notify players of needed updates for addons

src/input/device_config.cpp
Add tag name to log message. This might cause a crash / segmentation fault.
```
```
=> Fix missing argument in warning

src/karts/kart.cpp
=> Fix wrong win message in races only with 1 kart

src/input/gamepad_config.cpp, src/input/gamepad_config.hpp, src/input/gamepad_device.cpp, src/input/gamepad_device.hpp, src/input/sdl_controller.cpp, src/input/sdl_controller.hpp
Closes #4636 
As is apparently standard for racing wheels, this is a percentage between 0 and 100 indicating the strength with which the wheel will spring back. Modify the atribute in input.xml
```
```
=> Allow setting auto-center property for racing wheels (closes #4636)

lib/tinygettext/CMakeLists.txt
Explicitly pass STATIC to tinygettext add_library() call to make sure
it's always built as static, even when distro's cmake is configured to
build libs shared by default.
```
```
=> Always build tinygettext as a static library

data/skins/cartoon/stkskin.xml, data/skins/coal/stkskin.xml, data/skins/forest/stkskin.xml, data/skins/ocean/stkskin.xml, data/skins/peach/stkskin.xml, data/skins/ruby/stkskin.xml, src/graphics/irr_driver.cpp, src/guiengine/engine.cpp, src/guiengine/skin.cpp, src/guiengine/skin.hpp, src/io/file_manager.cpp, src/main.cpp, src/states_screens/options/options_screen_ui.cpp
Anything not provided or defined by a skin will be used from the defined base skin, if specified.
For example, if a skin provides a base_theme of "cartoon", any icons/buttons/etc. not provided by the skin will be pulled from "cartoon".
My goal is to make color variants of the Cartoon skin, but before this PR it would have required bundling an entire duplicate icon theme with each skin, now the skins can just specify `base_theme="cartoon"`.
```
Keep the above statement in the pull request comment for …
```
=> Allow specifying a base skin

src/graphics/glwrap.cpp
It seems AMD provides an equivalent to `NvOptimusEnablement` called `AmdPowerXpressRequestHighPerformance`
See https://gpuopen.com/learn/amdpowerxpressrequesthighperformance/
```
```
=> Request AMD GPU on Enduro Devices

src/graphics/stars.cpp, src/graphics/stars.hpp
This adds a little animation to stars that appear after a kart has been hit.
The animation is a subtle bouncing effect, with more intensity at then end:
https://user-images.githubusercontent.com/66701383/148719770-1882e2c0-772a-484e-becd-1fcb5dd78f01.mp4
```
```
=> Added animation to stars

src/items/item.cpp, src/items/item.hpp, src/items/item_manager.cpp, src/items/item_manager.hpp, src/tracks/track.cpp, src/utils/constants.hpp
This adds an animation when items respawn.
https://user-images.githubusercontent.com/66701383/148840908-b5c655dc-01f9-46df-893b-fe08b98a13cc.mp4
**Note:** With this animation alone, the only visual cue that happened when the item became pickable again was the resuming of rotation.
I wanted to add more visual cues to make it as intuitive as possible. I originally wanted to make the item much darker while respawning, then reverting back to normal brightness when the item was available again; however, I couldn't get this to work.
Instead, it works by making the item slightly smaller when respawning, then by taking its full size only when the respawn animation finished. I'm a bit unsatisfied with this option, but it seems to work.
If someone could help me with changing items' colors at …
=> Items animation

.gitignore
Clangd can be used to detect errors in real time while programming. It also offers useful warnings to help improve code quality.
It does, however, generate some files at the root of the repository. I added them to the `.gitignore` file in this PR.
If it can be useful for other developers as well, I'm offering my changes back to the repository.
```
```
=> Ignore clangd files

.github/workflows/windows.yml, tools/windows_installer/supertuxkart-64bit-mingw.nsi, tools/windows_installer/supertuxkart-github-actions.nsi, tools/windows_installer/supertuxkart-mingw.nsi
Winget relies on this value to get the version of a program.
If it's missing winget will just download the newest version even if the program is up to date.
See https://github.com/microsoft/winget-cli/issues/1255
```
```
=> Add DisplayVersion to Windows registry on install (+typo)

data/kart_characteristics.xml, data/stk_config.xml, src/config/stk_config.cpp, src/config/user_config.hpp, src/states_screens/race_gui.cpp, src/states_screens/race_gui_base.cpp
Hi,
i propose this PR in order to allow to customize the dashboard shown while racing
by editing local user config (`config.xml`).
The PR does (with motives):
- add size and display settings (center, right, hidden) for powerup icon  (motives below)
- powerup icon may strongly obstruct field of view with custom camera settings
- powerup icon doesn't provide any additional information if the option to show karts help powerup is active
- in Soccer Tournament  context, some players wish to remove the powerup icon in order to record the match as spectator (other gui elements are not obstructing but may be subject for future PR)
- move minimap display settings in user settings (motives below)
- minimap size is not similar to other core (mostly physics, rules and api) properties define in …
=> Minimap and powerup icon settings in user settings

src/online/link_helper.cpp
My general strategy of getting ports to work on Haiku is to just take advantage
of whatever makes things work on FreeBSD by adding an additional condition and
then fixing up things later once it compiles successfully. This generally
works, as Haiku contains FreeBSD headers for compatibility and code that
takes other operating systems into account other than Windows, Linux and OS X
and has a higher degree of POSIX compatibility tends to work on FreeBSD and
Haiku. This strategy is not perfect, and this commit proves it.
Haiku is the successor of BeOS, which, in turn, shows similarities to macOS
every now and then, as the company almost acquired Be, Inc., but later chose to
acquired NeXT, Inc. instead.
`xdg-open` is not available on Haiku the same way it is on FreeBSD and Linux.
With that in …
=> Fix URLs on Haiku

lib/irrlicht/source/Irrlicht/CImageLoaderSVG.cpp
Builds on `SERVER_ONLY` were failing:
```
/home/purple/stk-code/lib/irrlicht/source/Irrlicht/CImageLoaderSVG.cpp:16:10: fatal error: ge_main.hpp: No such file or directory
16 | #include "ge_main.hpp"
|          ^~~~~~~~~~~~~
```
```
```
=> CImageLoaderSVG: don't rescale on server

src/replay/replay_recorder.cpp
```
```
This should resolve #4758 - at least on my system it did :-)
=> ReplayRecorder: write correct number of transformation into "size"

src/guiengine/widgets/CGUIEditBox.cpp
The first two conditions made the whole if condition always true
I've copied the fix from the current implementation in libraqm
https://raw.githubusercontent.com/HOST-Oman/libraqm/master/src/raqm.c
```
```
=> Fix logical error in CGuiEditBox - libraqm implementation

lib/graphics_engine/src/ge_vulkan_array_texture.cpp, lib/graphics_engine/src/ge_vulkan_texture.cpp
```
```
I'm not really into vulkan, but this code does not build on FreeBSD/i386:
```
/work/usr/ports/games/supertuxkart/work/SuperTuxKart-1.4-rc1-src/lib/graphics_engine/src/ge_vulkan_texture.cpp:440:17: error: cannot initialize a variable of type 'VkImageView' (aka 'unsigned long long') with an rvalue of type 'nullptr_t'
VkImageView view_ptr = NULL;
^          ~~~~
1 error generated.
```
so these types are not pointers and may not be …
=> Initialize vulkan handles properly

android/make.sh
Run directly it fails with: `./make.sh: 203: Syntax error: "(" unexpected`
A scan on https://www.shellcheck.net/ shows too many issues, this needs to be redesigned a lot to be clean of bashisms
```
```
=> make.sh - specify interpreter directly

src/items/powerup.cpp
only deshield karts ahead of the kart firing the parachute
```
```
=> fix parachute powerup

src/modes/soccer_world.cpp
When the goal is scored, the ball is moved from its current position to its Blender position. If another goal line is intersected during this movement, it's apparently triggered too, causing double goals. This commit seems to fix it.
```
```
=> Avoid triggering other goal lines when the goal is already scored

data/supertuxkart.appdata.xml
```
```
The release entry for STK 1.4 was sadly not added before 1.4 was released. This is a problem for many package management formats that use AppData and will have to be manually patched. I am at least adding it now.
/cc @Benau
=> Add missing 1.4 release into AppData

src/network/protocols/client_lobby.cpp, src/network/protocols/server_lobby.cpp
```
```
---
When playing with some friends I noticed the bot names went as follows: "Bot", "Bot 1", "Bot 2" etc.
With these changes, it goes as follows instead: "Bot 1", "Bot 2", "Bot 3", etc.
=> Make bot names start at 1

lib/graphics_engine/include/vk_mem_alloc.h, lib/graphics_engine/src/ge_spm_buffer.cpp, lib/graphics_engine/src/ge_vulkan_array_texture.cpp, lib/graphics_engine/src/ge_vulkan_command_loader.cpp, lib/graphics_engine/src/ge_vulkan_depth_texture.cpp, lib/graphics_engine/src/ge_vulkan_draw_call.cpp, lib/graphics_engine/src/ge_vulkan_fbo_texture.cpp, lib/graphics_engine/src/ge_vulkan_mesh_cache.cpp, lib/graphics_engine/src/ge_vulkan_skybox_renderer.cpp, lib/graphics_engine/src/ge_vulkan_texture.cpp, lib/graphics_engine/src/ge_vulkan_texture_descriptor.cpp
Like other versions before, gcc 13 moved some includes around and as a result <stdexcept> and <cstdio> are no longer transitively included. Explicitly include them for std::runtime_error and snprintf.
```
```
=> Add missing includes to fix the build with gcc 13

data/gui/screens/help2.stkgui
```
```
Lap Trial wasn't mentioned in the 'game modes' section of the help screen, even though that Lap Trial was now introduced in the main game.
=> Add previously missing Lap Trial mode in game modes help screen

data/shaders/ssao.frag
this fixes opaque shadow rendering on drivers that implement mediump as 16bit
fixes #4855
```
```
=> declare some ssao.frag variables as highp to avoid precision issues

src/modes/world.cpp, src/modes/world.hpp
https://user-images.githubusercontent.com/66701383/233221592-f06f9031-9dcf-43d5-9d73-a173f1acae6d.mp4
The cursor will show back up whenever:
- The mouse is moved
- The game is paused
- The race finished
----------------------
This is probably not the best implementation, but it's a start.
Some things that could be improved:
- I'm currently using raw SDL_* calls in world.cpp, and I didn't #include SDL.h
- The time before the cursor disappears is stored in a macro; perhaps it could be configured
```
Keep …
```
=> Hide the cursor during gameplay

src/utils/log.cpp
I just added one line so it flushes the stdout after writing to it.
This fixes issues where it creates a backlog of piped output (e.g. if server is running through a wrapper or any sort of piped output)
```
```
=> Add fflush(stdout) after writing to stdout with printf

src/tracks/drive_graph.cpp
When setting sidewards-distance for a track to a negative value, this commit produces an effect that the starting grid is mirrored compared to the grid of corresponding positive value.
It may be useful for the tracks where the first turn goes right. For some of them (e.g. Oliver's Math Class), the first starting position is not the best one.
As much as I'm aware, currently all existing tracks use positive sidewards distance, so this shouldn't cause side effects for them (until they are updated, or until there is a track with negative sidewards distance).
```
This includes your …
```
=> Fix start positions for negative sidewards distance

src/guiengine/skin.cpp, src/guiengine/skin.hpp, src/guiengine/widgets/progress_bar_widget.cpp
Issue #4891 seems like a result of using the same SkinContainer to render different parts for progress bar, so SkinContainer should be a list.
=> Add multiple skin container & Fix #4891

src/network/protocols/server_lobby.cpp, src/network/protocols/server_lobby.hpp
This fixes the following issues related to voting for a map in the server lobby:
1. When several maps have the same number of votes, the code currently iterates over them and picks the next one with probability $\frac{1}{2}$, so if there are $n$ different votes, $i$-th of them is chosen with probability $2^{\max(i, 2)} / 2^{n + 1}$. This PR changes all probabilities to $\frac{1}{n}$.
2. When the majority exists for maps, for lap counts, and for directions, but there's no vote with exactly the same map, lap count, and direction, the first vote (that is, the vote of players with smallest host id?) was picked instead. This PR postpones the decision until the voting is over.
I also tried to get rid of repeated code, thus moved it to another function.
```
By creating a pull request in …
```
=> Fixes for handleAllVotes

lib/irrlicht/source/Irrlicht/CIrrDeviceSDL.cpp, lib/irrlicht/source/Irrlicht/COGLES2Driver.cpp, lib/irrlicht/source/Irrlicht/COGLES2Driver.h
```
```
This commit tries to fix the exit/resolution-change crash due to GLES functions being cleaned up before being called to release GLES resources.
=> Fix exit crash when built for GLES2 on Linux

.github/workflows/apple.yml
```
```
I do not know if this fixes the MacOS builds. Seems too simple a fix.
=> [DRAFT] Use relative path for MacOS workflow

src/network/database_connector.cpp, src/network/database_connector.hpp, src/network/protocols/server_lobby.cpp, src/network/protocols/server_lobby.hpp
Here, I split the database-related code previously located in ServerLobby implementation into logic part, which stayed in ServerLobby, and database part (forming queries, all types of sqlite3_* functions), which moved to a new DatabaseConnector class. Apart from that, I reused some code previously repeated while making queries of same type and while binding values (by adding two auxiliary structures), and added some doxygen comments.
I felt like making a separate class for that purpose would do better than not making it, as there a few more variables to keep track of than just database handle, and passing database handle to each of many functions would probably be too long in terms of code.
The amount of changes is pretty big, so I suppose that despite I did some testing, it requires even …
=> Separate database-related code from ServerLobby

data/supertuxkart.appdata.xml
Add launchable tag that is now required by many AppStream parsers.
```
```
/cc @Benau
Also consider renaming the AppData file (and the app id) to a rDNS (net.supertuxkart.SuperTuxKart) format. The non-rDNS one is deprecated.
=> Update AppData file

src/config/user_config.hpp, src/main.cpp, src/states_screens/race_result_gui.cpp
Adding `--benchmark` to command-line options to automatically start benchmark mode, set unlimited fps, save results and exit.
Closes #5177 
```
```
=> Add benchmark mode to command-line options

data/gui/screens/arenas.stkgui, data/gui/screens/karts.stkgui, data/gui/screens/online/network_karts.stkgui, data/gui/screens/race_setup.stkgui, data/gui/screens/tracks_and_gp.stkgui, src/config/favorite_status.cpp, src/config/favorite_status.hpp, src/config/player_profile.cpp, src/config/player_profile.hpp, src/guiengine/widgets/player_kart_widget.cpp, src/karts/kart_properties.cpp, src/karts/kart_properties_manager.cpp, src/karts/kart_properties_manager.hpp, src/states_screens/arenas_screen.cpp, src/states_screens/arenas_screen.hpp, src/states_screens/kart_selection.cpp, src/states_screens/kart_selection.hpp, src/states_screens/tracks_and_gp_screen.cpp, src/tracks/track.cpp, src/tracks/track_manager.cpp, src/tracks/track_manager.hpp
=> Implement kart grouping/searching/favorite

INSTALL.md
```
```
Hi, I find these instructions helpful for Powershell+LLVM-MinGW users when building on Windows.
=> doc: add instructions to build on Windows using LLVM MinGW from powershell/cmd

data/graphical_restrictions.xml
Android Emulator supports proper hardware acceleration nowadays, we shouldn't be forcing the legacy pipeline if it's not needed.
```
```
=> graphical_restrictions.xml: Remove restrictions for Android Emulator

data/gui/screens/arenas.stkgui, data/gui/screens/karts.stkgui, data/gui/screens/online/network_karts.stkgui, data/gui/screens/tracks.stkgui, src/states_screens/kart_selection.cpp, src/states_screens/online/tracks_screen.cpp
=> Add favorite to network track & Fix Android favorite kart

src/network/protocols/ranking.cpp, src/network/protocols/ranking.hpp, src/network/protocols/server_lobby.cpp, src/network/protocols/server_lobby.hpp
This patch reduces the length of server_lobby.cpp to be below 5k lines.
I did not change the ranking system itself.
For obvious reasons, I could test only a modified version of this branch. More testing is probably required. But it seems to not crash...
```
```
=> Move ranking related stuff out of server_lobby.cpp

src/config/user_config.hpp, src/main.cpp
Also cleaned up the help text
```
```
Changes as per this bug: https://github.com/supertuxkart/stk-code/issues/5213
Please let me know if the style is too off or any other changes needed to be made. Thank you.
=> Added in feature to assign keyboard or gamepad with the -N or -R option

lib/bullet/src/BulletCollision/BroadphaseCollision/btAxisSweep3.h, lib/bullet/src/BulletCollision/BroadphaseCollision/btMultiSapBroadphase.cpp, lib/bullet/src/BulletCollision/BroadphaseCollision/btOverlappingPairCache.cpp, lib/bullet/src/BulletCollision/BroadphaseCollision/btOverlappingPairCache.h, lib/bullet/src/BulletCollision/BroadphaseCollision/btSimpleBroadphase.cpp
Previously some of them were commented in one file without realizing they are extern in another file.
```
```
=> Remove unused variables, fix #5161

src/guiengine/skin.cpp
```
```
This follows the proposal in #5109 to remove the glow under the five main menu options, and derives its approach from the recommendation given when #5222 was closed.
To see if an icon button has a focus image specified, I check if the size of `m_properties[PROP_FOCUS_ICON]` exceeds 0, as is done when assinging `m_highlight_texture` in `icon_button_widget.cpp`.
=> Removed glow under main menu options

NETWORKING.md, tools/generate-countries-table.py, tools/generate-ip-mappings.py
I have to explain others what to change in scripts otherwise.
I doubt it works somehow differently on other systems, but just in case it does, some testing could be welcome
```
```
=> Minor fixes for database initialization scripts

data/shaders/IBL.frag, data/shaders/bilateralH.comp, data/shaders/bilateralH.frag, data/shaders/bilateralV.comp, data/shaders/bilateralV.frag, data/shaders/combine_diffuse_color.frag, data/shaders/degraded_ibl.frag, data/shaders/ssao.frag, src/graphics/lighting_passes.cpp, src/graphics/lighting_passes.hpp, src/graphics/post_processing.cpp, src/graphics/post_processing.hpp, src/graphics/shader_based_renderer.cpp, src/guiengine/skin.cpp, src/tracks/track.cpp
How could the current SSAO avaliable to users?
```
```
=> Make SSAO correct

src/network/protocols/server_lobby.cpp
~~I suppose it's fine to check it naively, as we don't have many players inside one peer, and as the number of messages per peer can already be limited in the server config (and is not big in general).~~
~~If there will be a need in many similar checks, I can make a separate data structure for that.~~
Apparently only one username can appear in the message. There's no need to send it, either, but removing the name from the messages would break the network protocol with other 1.x versions, so I'm just checking one username now.
---
You can test it against the [client](https://github.com/kimden/stk-code/tree/impersonation) modified to reproduce this issue.
```
GNU General Public License version 3 or …
```
=> Fix #5121: Check if chat messages start with 'name: '

src/network/protocols/ranking.hpp
Without the chnage the build fails on upcoming `gcc-15` as:
/build/source/src/network/protocols/ranking.hpp:31:5: error: 'uint32_t' does not name a type
31 |     uint32_t online_id;
|     ^~~~~~~~
```
```
=> src/network/protocols/ranking.hpp: add missing `<stdint.h>` include

src/karts/ghost_kart.cpp, src/karts/ghost_kart.hpp, src/karts/kart.cpp
=> Fix #5252 & #5189

src/graphics/irr_driver.cpp, src/guiengine/engine.cpp, src/guiengine/engine.hpp, src/karts/kart_model.cpp, src/karts/kart_properties_manager.cpp, src/main.cpp
I don't know how to get the number of icons in advance, nor I can make proper animations, so for now the jump in size is like that. I will add more commits if I find out how.
---
I made this commit a few months ago, I remember nothing apart from description but maybe you find it useful enough
```
```
=> Make loading screen icons fit ~40% of it

data/gui/screens/tracks_and_gp.stkgui, src/states_screens/tracks_and_gp_screen.cpp
```
```
##
Adds the "random track" button outside the track chooser, because once you have >100 tracks, then finding the "random track" button is very annoying. I can't count the amount of times I had to scrool through my whole "gallery" of maps, just to find the "random track" button.
The code must be cleaned up (the button functionality is very similar to the one in the track chooser and I didn't know what's the best way to make it …
=> added random track button outside the track chooser

src/graphics/shader_files_manager.cpp
Currently we do not add precision description to sampler2D's, and the default precision defined by ESSL spec is lowp.
Experimentation on an Imagination AXM-8-256 GPU shows that the advanced pipeline needs highp sampler2D, otherwise some distant objects will glitch (noticable at the start point of black_forest map).
Manually add precision modifiers for sampler2D to fix the glitch.
Tested on Eswin EIC7700 with X11+EGL+GLES with Imagination DDK 23.2 driver.
P.S. setting mediump instead of highp on sampler2D's seems to be not enough for resolving the glitch; maybe hardwares w/o highp support need to be forbidden from advanced pipeline or some shaders need to be rewritten to be mediump-safe.
```
GNU …
```
=> Fix GLES sampler precision issue for advanced pipeline
